"""Original module reference notes, available beside every exercise."""

REFERENCES = {
    'basics': [
        ('Values and types', 'count = 3\nprice = 4.5\nname = "Tea"\nprint(type(price).__name__)', 'int represents whole numbers, float represents approximate decimal numbers, and str represents text. Quoted digits are text. Inspect types when an operation behaves unexpectedly.'),
        ('Calculations and assignment', 'subtotal = price * count\ntotal = subtotal + 2\ncount += 1', 'The right-hand expression is evaluated before its result is assigned to the name on the left. Multiplication and division happen before addition and subtraction. Parentheses make a different grouping explicit. Changing count later does not recalculate an earlier subtotal.'),
        ('Division', 'whole = 17 // 5\nremainder = 17 % 5\nratio = 17 / 5', '/ performs ordinary division. // floors the quotient. % returns the remainder. For these nonnegative inputs, whole groups and leftovers reconstruct the original quantity.'),
        ('Convert, calculate, then display', 'value = float("12.50")\nquantity = int("3")\nprint(f"Total: {value * quantity:.2f}")', 'Convert input text before arithmetic. Use int for integer text and float for decimal text. The :.2f format displays two decimal places without turning the original number into a string.'),
        ('Text operations', 'label = "  SALES  ".strip().lower()\nparts = "a|b|c".split("|")\ndisplay = ", ".join(parts)', 'String methods return new strings. strip removes outer whitespace, lower changes case, split returns a list, and join combines strings with a separator. Keep the result by assigning it.')],
    'flow': [
        ('Choose a branch', 'if amount > limit:\n    status = "over"\nelif amount == limit:\n    status = "equal"\nelse:\n    status = "under"', 'Use a colon after each branch header and four spaces for its body. Only the first matching branch runs. Test values below, at, and above a boundary. = assigns; == compares.'),
        ('Combine rules', 'allowed = member and spend >= 50\nready = pickup or has_address\nmissing = not has_address', 'and requires both conditions, or requires at least one, and not reverses a truth value. Name complicated conditions and inspect their parts when debugging. Use Boolean True and False without quotes.'),
        ('Accumulate and filter', 'total = 0\nlarge = []\nfor value in values:\n    total += value\n    if value >= 20:\n        large.append(value)', 'Initialise accumulators before the loop. Put only repeated work inside it. A nested if needs an additional indentation level. Print a final total after the loop if you want one summary.'),
        ('Ranges and positions', 'for day, value in enumerate(values, start=1):\n    print(day, value)\n\nfor number in range(2, 11, 2):\n    print(number)', 'range excludes its stop. enumerate keeps an item and counter together. Choose a one-based counter for human-facing labels and remember that ordinary list indices still start at zero.'),
        ('Stopping conditions', 'while balance < target:\n    balance += deposit\n\nfor value in values:\n    if value > threshold:\n        first = value\n        break', 'A while loop needs a state update that eventually makes its condition false. break stops the current loop. Initialise a no-match result, such as None, before a search.')],
    'collections': [
        ('Index and slice', 'first = values[0]\nlast = values[-1]\nwindow = values[1:4]', 'Indices begin at zero. A negative index counts from the end. Slices include the start and exclude the stop. Unlike indexing, slicing beyond the list boundary safely returns the available portion.'),
        ('Mutation versus copying', 'revised = original.copy()\nrevised.append(4)\nrevised.extend([5, 6])\nlast = revised.pop()', 'Assignment alone creates another reference to the same list. copy creates a new outer list. append adds one item, extend adds several, and pop removes and returns an item. Shallow copies still share nested mutable objects.'),
        ('Dictionary views', 'for name, quantity in stock.items():\n    print(name, quantity)\ntotal = sum(stock.values())', 'Iterating a dictionary directly yields keys. items yields key-value pairs, and values yields the values alone. get(key, default) handles an absent key; it does not replace an existing None.'),
        ('Grouping and counting', 'counts = {}\nfor label in labels:\n    counts[label] = counts.get(label, 0) + 1', 'A frequency table adds one per record. A grouped total adds a measurement instead. Normalise labels before grouping, and reconcile grouped totals with the original observation count or total.'),
        ('Comprehensions, sets, and sorting', 'cleaned = [x.strip() for x in names if x.strip()]\nmissing = expected - received\nranked = sorted(rows, key=lambda row: row["name"])', 'A comprehension transforms and optionally filters. Sets handle uniqueness and membership without preserving a presentation order. sorted returns a new list; key selects the comparison value.')],
    'functions': [
        ('Return data to a caller', 'def line_total(price, quantity):\n    return price * quantity\n\namount = line_total(5, 3)', 'Parameters receive inputs for each call. return sends a result back and exits the function. print only displays a value. A function without an executed return produces None.'),
        ('Defaults and keywords', 'def final(amount, fee=4, discount=0):\n    return amount + fee - discount\n\nresult = final(40, discount=5)', 'Defaults apply only to omitted arguments. Keyword arguments document which setting each value belongs to. Avoid mutable default lists or dictionaries because they would be shared between calls.'),
        ('Local state and guard clauses', 'def average(values):\n    if not values:\n        return None\n    return sum(values) / len(values)', 'Initialise accumulators inside a function so repeated calls start fresh. A guard handles an edge case before the ordinary calculation. State whether empty input returns None, zero, an empty container, or an error.'),
        ('Validation and exceptions', 'try:\n    number = int(text)\nexcept ValueError:\n    number = None\n\nif amount < 0:\n    raise ValueError("amount must be nonnegative")', 'Catch a specific expected failure. Raise a clear error when an input violates your function’s contract. Tests should cover valid inputs, boundaries, empty inputs, and repeated calls.'),
        ('Compose small operations', 'taxed = add_tax(subtotal(items))\nhours, minutes = split_minutes(135)', 'A function can reuse another function instead of duplicating its calculation. A tuple returns a few ordered results; a dictionary often makes many named results clearer.')],
    'files': [
        ('File modes and encoding', 'with open("notes.txt", encoding="utf-8") as file:\n    text = file.read()\n\nwith open("events.txt", "a", encoding="utf-8") as file:\n    file.write("done\\n")', 'Read mode is the default. w replaces a file; a appends. with closes the file when the block ends. A write adds exactly the supplied text, so include newlines deliberately. Practice files are recreated for every attempt.'),
        ('Read CSV records', 'import csv\nwith open("data.csv", newline="", encoding="utf-8") as file:\n    rows = list(csv.DictReader(file))', 'DictReader uses the header as keys and understands quoting. Numeric fields are returned as text: convert before arithmetic. Parse records instead of concatenating or splitting raw CSV text.'),
        ('Write CSV records', 'with open("out.csv", "w", newline="", encoding="utf-8") as file:\n    writer = csv.DictWriter(file, fieldnames=["name", "qty"])\n    writer.writeheader()\n    writer.writerows(rows)', 'fieldnames establishes the output column order. Write one header for the whole output, even when combining many input files. Read the output back to validate its logical contents.'),
        ('JSON files versus JSON text', 'data = json.loads(text)\ntext = json.dumps(data)\n# json.load(file) reads a file.\n# json.dump(data, file) writes a file.', 'JSON preserves numbers, strings, lists, objects, Booleans, and null (None in Python). Inspect the outer structure before selecting nested records. Valid JSON syntax does not guarantee a valid application schema.'),
        ('Audit excluded data', 'valid = []\nrejected = 0\nfor text in inputs:\n    try:\n        valid.append(int(text))\n    except ValueError:\n        rejected += 1', 'Keep counts or details of excluded observations. Distinguish missing optional fields from missing required fields. A default should reflect an explicit rule rather than silently hide a broken export.')],
    'analysis': [
        ('Describe centre and spread', 'from statistics import mean, median, pstdev\ncentre = mean(values)\ntypical = median(values)\nspread = pstdev(values)', 'A mean responds strongly to unusually large or small observations. A median describes the middle. Spread reveals variation hidden by the centre. pstdev describes a complete population; stdev estimates spread from a sample.'),
        ('Missing is different from zero', 'valid = [x for x in values if x is not None]\nmissing_count = len(values) - len(valid)', 'Filter explicitly for None if that is the missing-data marker. Filtering on truthiness also removes zero. Document excluded data and define what happens when no valid observations remain.'),
        ('Ratios and change', 'share = part / whole * 100\nchange = (current - previous) / previous * 100', 'The denominator determines the question. Percentage change uses the previous period as its baseline. When that baseline is zero, the ordinary formula is undefined; choose an explicit missing-result policy.'),
        ('Weighted and grouped means', 'weighted = sum(m * n for m, n in zip(means, counts)) / sum(counts)', 'Use group sizes when combining group means. Within each group, divide its total by its own count. Keep counts alongside averages so readers understand the evidence behind each measurement.'),
        ('Time order and ranking', 'window = values[end-3:end]\nranked = sorted(rows, key=lambda r: (-r["score"], r["name"]))', 'Moving windows require the original chronological order. Rankings need an explicit tie rule. An unusual value is a candidate for investigation, not automatic evidence of a data error.')],
    'pandas': [
        ('Inspect and select', 'df = pd.read_csv("data.csv")\nprint(df.shape, df.columns.tolist())\nprint(df.head())\nrow = df.iloc[0]\nvalue = df.loc[label, "revenue"]', 'A DataFrame is a table and a Series is a column-like sequence. loc uses labels; iloc uses positions. Select multiple columns with df[["a", "b"]]. Inspect types before assuming a column is numeric.'),
        ('Filter and sort', 'selected = df[(df["region"] == "North") & (df["revenue"] >= 100)]\nselected = selected.sort_values("revenue", ascending=False)', 'Use & or | for elementwise conditions and put each condition in parentheses. Python and/or expect single truth values. Sort explicitly whenever the output order matters.'),
        ('Clean under a stated policy', 'df["name"] = df["name"].str.strip().str.lower()\ndf["amount"] = pd.to_numeric(df["amount"], errors="coerce")\nclean = df.dropna(subset=["amount"]).copy()', 'Coercion turns invalid numeric text into missing values. Count rejected records before dropping them. Use column-specific fill rules. drop_duplicates should use the key that defines a unique business record.'),
        ('Group and connect tables', 'summary = df.groupby("region").agg(total=("revenue", "sum")).reset_index()\njoined = orders.merge(products, on="product_id", how="left", validate="many_to_one")', 'Named aggregation creates readable summaries. A left join preserves left-side rows. Check unmatched keys and row counts after joining; duplicate lookup keys can unexpectedly multiply records.'),
        ('Dates and export', 'df["date"] = pd.to_datetime(df["date"], errors="coerce")\ndf["month"] = df["date"].dt.strftime("%Y-%m")\nsummary.to_csv("summary.csv", index=False)', 'Parse dates before date operations. Include the year when grouping by month. index=False excludes pandas’ internal index from a CSV export; reset_index(drop=True) removes old row labels without adding a column.')],
    'automation': [
        ('Choose a file scope', 'root = Path("inbox")\ndirect = root.glob("*.csv")\nrecursive = root.rglob("*.csv")', 'iterdir lists direct children, glob matches a pattern, and rglob includes descendants. Check is_file when directories are not valid inputs. Use as_posix for portable forward-slash display paths.'),
        ('Plan before applying', 'destination = Path(item["destination"])\nif not destination.exists():\n    destination.parent.mkdir(parents=True, exist_ok=True)\n    shutil.copy2(item["source"], destination)', 'Generate a dry-run plan, inspect conflicts, then apply it. State whether existing files should be skipped or replaced. copy2 preserves originals; repeated runs need an explicit duplicate policy. The practice fixtures are disposable.'),
        ('Dates and durations', 'end = date.fromisoformat("2026-03-03")\nstart = end - timedelta(days=6)', 'Use date libraries for month boundaries and leap years. Define whether a reporting range includes its endpoints. Date validation is different from merely reshaping the text of a filename.'),
        ('Text patterns', 'ids = re.findall(r"INV-(\\d{3})(?!\\d)", text)\nlabel = re.sub(r"\\s+", " ", text).strip()', 'A regex should describe both matches and important near-matches. Raw strings preserve backslashes. Keep identifiers as text when leading zeros have meaning. Normalise whitespace only where that fits the data.'),
        ('Make work auditable', 'data = path.read_bytes()\ndigest = sha256(data).hexdigest()\nsize = len(data)', 'Record copied, skipped, and failed outcomes. Content hashes compare bytes independently of filenames. A manifest can document the inputs to a run; large files should be hashed in streamed chunks.')],
    'web': [
        ('HTML structure and escaping', 'title = f"<h1>{escape(name)}</h1>"\nfield = f\'<input value="{escape(text, quote=True)}">\'', 'Tags define structure, while inserted text must be escaped for its context. Quote attribute values and escape quotes inside them. This introduction generates text locally rather than running a deployed website.'),
        ('Parse and construct URLs', 'parts = urlsplit(url)\nparams = parse_qs(parts.query)\nregion = params.get("region", ["all"])[0]\nquery = urlencode({"q": term})', 'A URL path and query are separate. parse_qs returns lists because keys can repeat. urlencode protects special characters when constructing a query. Do not assemble URLs by concatenating raw values.'),
        ('Requests and responses', 'response = {"status": 200, "headers": {"Content-Type": "application/json"}, "body": json.dumps(data)}', 'A request includes a method and path. A response includes a status, headers, and body. 404 means the route is unknown; 405 means the method is unsupported on a known route. JSON body text differs from an in-memory dictionary.'),
        ('Validate before using input', 'data = json.loads(body)\nif not isinstance(data, dict):\n    raise ValueError("expected an object")', 'Syntactically valid JSON can still have the wrong shape. Check required fields and types before calling their methods. Keep data selection and formatting in separate functions so each can be tested.'),
        ('Move toward a real application', 'selected = filter_sales(rows, region)\nbody = render_rows(selected)', 'The course models routing, request parsing, validation, selection, and rendering as local functions. A framework can later connect these pieces to HTTP, but real applications also need persistence, access control, and operational design.')]
}
