"""Additional applied practice; all datasets are original, local fixtures."""


def add_applied(add):
    add('pandas', 'table', 'inspect', 'Inspect a table before calculating',
        'Before transforming a table, inspect its shape, column names, and a few rows. A DataFrame may contain text where you expected numbers or more rows than an export description suggests. shape returns row and column counts; columns lists the labels; head(n) selects the first n rows without changing the source. Inspection is a separate step from analysis, not wasted preparation.',
        'print(df.shape)\nprint(df.columns.tolist())\nprint(df.head(2))',
        ['Set `row_count` and `column_count` from `df.shape`.', 'Set `columns` to a list of the column names.', 'Set `preview` to the first two rows of `df`.'],
        'import pandas as pd\ndf = pd.DataFrame({"product": ["Tea", "Cake", "Coffee"], "units": [2, 1, 4]})\n',
        'import pandas as pd\ndf = pd.DataFrame({"product": ["Tea", "Cake", "Coffee"], "units": [2, 1, 4]})\nrow_count, column_count = df.shape\ncolumns = df.columns.tolist()\npreview = df.head(2)',
        [('Inspect dimensions', 'assert row_count == 3 and column_count == 2'), ('Inspect labels', 'assert columns == ["product", "units"]'), ('Preview without losing rows', 'assert preview["product"].tolist() == ["Tea", "Cake"] and len(df) == 3')],
        ['shape is a property, not a method call.', 'Convert df.columns with tolist().', 'head(2) selects two rows.'],
        'The preview gives you a small, concrete view of the data while the full DataFrame remains available for later calculations.',
        ['shape describes the table dimensions.', 'columns reveals the names that later expressions must use.', 'head lets you inspect a manageable sample.'], 'A short preview does not prove that later rows have the same data quality.')
    add('pandas', 'table', 'loc-iloc', 'Separate labels from positions',
        'loc selects by row and column labels; iloc selects by integer positions. These coincide only when the index labels happen to match the positions. After filtering or loading a custom index, confusing them can produce the wrong row or a KeyError. Read the index as well as the displayed row order before choosing the selector.',
        'df = pd.DataFrame({"value": [10, 20]}, index=[100, 200])\nprint(df.loc[100, "value"])  # 10\nprint(df.iloc[0, 0])         # 10',
        ['Set `by_label` to the `sales` value at index label 20.', 'Set `by_position` to the `sales` value in the first row.', 'Set `chosen` to a `DataFrame` containing only `city` and `sales`, in that order.'],
        'import pandas as pd\ndf = pd.DataFrame({"city": ["A", "B", "C"], "sales": [10, 30, 20], "cost": [4, 8, 6]}, index=[10, 20, 30])\n',
        'import pandas as pd\ndf = pd.DataFrame({"city": ["A", "B", "C"], "sales": [10, 30, 20], "cost": [4, 8, 6]}, index=[10, 20, 30])\nby_label = df.loc[20, "sales"]\nby_position = df.iloc[0]["sales"]\nchosen = df[["city", "sales"]]',
        [('Select a label', 'assert by_label == 30'), ('Select a position', 'assert by_position == 10'), ('Choose ordered columns', 'assert chosen.columns.tolist() == ["city", "sales"] and len(chosen) == 3')],
        ['Use loc for the label 20.', 'Use iloc[0] for the first row.', 'Double brackets select a list of columns as a DataFrame.'],
        'Index labels are identifiers, not necessarily row numbers. Selecting explicitly prevents errors after sorting or filtering.',
        ['The first row has label 100 but position 0.', 'loc uses the label.', 'iloc uses the position.'], 'Label slices with loc can include their endpoint, unlike ordinary positional slices.')
    add('pandas', 'select', 'rename', 'Give columns consistent names',
        'Column names often arrive with spaces and inconsistent capitalisation. rename(columns=mapping) makes a deliberate mapping from source names to useful internal names. It returns a new DataFrame unless you request in-place modification. A clear schema makes later expressions shorter and reduces typing mistakes. Preserve the raw table if you need to compare it with the cleaned one.',
        'clean = raw.rename(columns={"Unit Price": "unit_price"})',
        ['Create `clean` by renaming `Product Name` to `product` and `Units Sold` to `units`.', 'Keep `raw` unchanged.', 'Calculate `total_units` from the new `units` column.'],
        'import pandas as pd\nraw = pd.DataFrame({"Product Name": ["Tea", "Cake"], "Units Sold": [3, 2]})\n',
        'import pandas as pd\nraw = pd.DataFrame({"Product Name": ["Tea", "Cake"], "Units Sold": [3, 2]})\nclean = raw.rename(columns={"Product Name": "product", "Units Sold": "units"})\ntotal_units = clean["units"].sum()',
        [('Apply the schema mapping', 'assert clean.columns.tolist() == ["product", "units"]'), ('Preserve the source schema', 'assert raw.columns.tolist() == ["Product Name", "Units Sold"]'), ('Use the renamed column', 'assert total_units == 5')],
        ['Pass a dictionary to columns=.', 'Assign the returned DataFrame to clean.', 'Sum clean["units"].'],
        'A documented column mapping separates source-specific formatting from the names your analysis uses.',
        ['The mapping key is the old name.', 'The mapping value is the new name.', 'Assignment keeps the renamed result.'], 'Calling rename without keeping its returned result leaves the original DataFrame unchanged.')
    add('pandas', 'clean', 'deduplicate', 'Define what makes a record unique',
        'Duplicate rows and duplicate business identifiers are different problems. drop_duplicates(subset=[...], keep="last") retains the final row for each specified key. The meaning of last depends on row order, so sort by time first when recency is the rule. Here the records are already ordered from older to newer and email is the unique key.',
        'latest = df.drop_duplicates(subset=["email"], keep="last")',
        ['Normalise `email` by stripping and lowercasing it.', 'Create `latest` with the last row for each `email`, preserving the order of retained rows.', 'Reset `latest`’s index without adding an index column.'],
        'import pandas as pd\ndf = pd.DataFrame({"email": [" A@X.COM ", "b@x.com", "a@x.com"], "visits": [1, 3, 5]})\n',
        'import pandas as pd\ndf = pd.DataFrame({"email": [" A@X.COM ", "b@x.com", "a@x.com"], "visits": [1, 3, 5]})\ndf["email"] = df["email"].str.strip().str.lower()\nlatest = df.drop_duplicates(subset=["email"], keep="last").reset_index(drop=True)',
        [('Keep the last normalised record', 'assert latest["email"].tolist() == ["b@x.com", "a@x.com"] and latest["visits"].tolist() == [3, 5]'), ('Reset the index cleanly', 'assert latest.index.tolist() == [0, 1] and latest.columns.tolist() == ["email", "visits"]')],
        ['Clean the key before finding duplicates.', 'Use subset=["email"] and keep="last".', 'Finish with reset_index(drop=True).'],
        'Duplicate detection should reflect the meaning of a record. Looking at every column would miss the repeated email because its visits value changed.',
        ['subset identifies the uniqueness key.', 'keep="last" chooses the final occurrence.', 'Other columns come from that retained row.'], 'Last in file order does not automatically mean latest in time.')
    add('pandas', 'clean', 'fill-policy', 'Fill a missing value under a stated rule',
        'fillna supplies a replacement for missing values. The choice is a data policy, not merely a cleaning command. Replacing a missing discount with zero may be justified when absence means no discount; replacing unknown revenue with zero can distort totals. Here the contract says a missing discount means zero, while missing revenue must remain missing.',
        'df["discount"] = df["discount"].fillna(0)',
        ['Replace missing `discount` values with zero.', 'Create `net` as `revenue - discount`.', 'Keep the unknown `revenue` and its `net` result missing. Set `missing_revenue` to their source count.'],
        'import pandas as pd\ndf = pd.DataFrame({"revenue": [100, 50, None], "discount": [10, None, None]})\n',
        'import pandas as pd\ndf = pd.DataFrame({"revenue": [100, 50, None], "discount": [10, None, None]})\ndf["discount"] = df["discount"].fillna(0)\ndf["net"] = df["revenue"] - df["discount"]\nmissing_revenue = int(df["revenue"].isna().sum())',
        [('Fill only discounts', 'assert df["discount"].tolist() == [10, 0, 0]'), ('Calculate known net values', 'assert df["net"].iloc[:2].tolist() == [90, 50]'), ('Preserve unknown revenue', 'assert missing_revenue == 1 and pd.isna(df["revenue"].iloc[2]) and pd.isna(df["net"].iloc[2])')],
        ['Select only the discount column for fillna.', 'Subtract columns normally; missing revenue propagates.', 'isna().sum() counts missing entries.'],
        'The different fields have different missing-value meanings. A blanket df.fillna(0) would silently change the revenue policy.',
        ['The operation targets one column.', 'Only missing entries receive the replacement.', 'Known values remain unchanged.'], 'A convenient default is not automatically a valid interpretation of missing data.')
    add('pandas', 'clean', 'aggregations', 'Calculate several summaries per group',
        'Named aggregation lets groupby produce several measurements with readable output names. Each output name maps to a column and an operation. Keep counts alongside means so you can see how much data supports each average. After grouping, reset_index returns the group keys to ordinary columns, making the result easier to inspect and export.',
        'summary = df.groupby("team").agg(total=("value", "sum"), count=("value", "count")).reset_index()',
        ['Group by `region` into `summary` with total revenue, average revenue, and order count.', 'Name the columns `region`, `total`, `average`, `order_count`.', 'Sort regions alphabetically and reset the index.'],
        'import pandas as pd\ndf = pd.DataFrame({"region": ["North", "South", "North"], "revenue": [10, 30, 20]})\n',
        'import pandas as pd\ndf = pd.DataFrame({"region": ["North", "South", "North"], "revenue": [10, 30, 20]})\nsummary = df.groupby("region").agg(total=("revenue", "sum"), average=("revenue", "mean"), order_count=("revenue", "count")).reset_index().sort_values("region").reset_index(drop=True)',
        [('Keep descriptive column names', 'assert summary.columns.tolist() == ["region", "total", "average", "order_count"]'), ('Calculate all group summaries', 'assert summary.to_dict("records") == [{"region": "North", "total": 30, "average": 15.0, "order_count": 2}, {"region": "South", "total": 30, "average": 30.0, "order_count": 1}]')],
        ['Use .agg() after groupby.', 'Each output name receives ("revenue", operation).', 'Use operations "sum", "mean", and "count".'],
        'Both regions have revenue of 30, but their average order sizes differ. Multiple measurements reveal what one total hides.',
        ['groupby chooses which rows belong together.', 'agg applies each requested operation.', 'Named outputs avoid ambiguous column labels.'], 'count excludes missing values; size counts rows, including rows whose measurement is missing.')
    add('pandas', 'clean', 'merge', 'Connect two tables by a key',
        'A merge connects records using a shared key. A left join keeps every row from the left table and adds matching fields from the right. Unmatched fields become missing. When the right table should have one row per key, validate="many_to_one" checks that assumption and catches duplicate lookup keys before they multiply your rows.',
        'joined = orders.merge(products, on="product_id", how="left", validate="many_to_one")',
        ['Left-join `orders` to `products` on `product_id`, storing the result in `joined`.', 'Calculate `revenue` from `qty * price`.', 'Set `unmatched` to the count of rows without a matching price. Keep unmatched orders.'],
        'import pandas as pd\norders = pd.DataFrame({"product_id": [1, 2, 1, 9], "qty": [2, 1, 3, 1]})\nproducts = pd.DataFrame({"product_id": [1, 2], "price": [5, 8]})\n',
        'import pandas as pd\norders = pd.DataFrame({"product_id": [1, 2, 1, 9], "qty": [2, 1, 3, 1]})\nproducts = pd.DataFrame({"product_id": [1, 2], "price": [5, 8]})\njoined = orders.merge(products, on="product_id", how="left", validate="many_to_one")\njoined["revenue"] = joined["qty"] * joined["price"]\nunmatched = int(joined["price"].isna().sum())',
        [('Retain every order', 'assert len(joined) == 4 and joined["product_id"].tolist() == [1, 2, 1, 9]'), ('Calculate matched revenue', 'assert joined["revenue"].iloc[:3].tolist() == [10, 8, 15]'), ('Expose the unmatched order', 'assert unmatched == 1 and pd.isna(joined["revenue"].iloc[3])')],
        ['Use how="left" to preserve the orders.', 'Multiply qty and price after merging.', 'Count missing prices with isna().sum().'],
        'The missing product is visible instead of silently dropped. Row-count and match-rate checks are important companions to a join.',
        ['The key identifies matching product records.', 'A left join preserves left-side observations.', 'Validation checks the expected relationship between tables.'], 'An inner join would remove unmatched orders and could make totals look better than the underlying data quality.')
    add('pandas', 'clean', 'monthly-review', 'Checkpoint · build a monthly summary',
        'Dates arrive as text but need date-aware operations for grouping and ordering. pd.to_datetime converts valid text into timestamps. With errors="coerce", invalid dates become missing. The .dt accessor applies date operations to a Series; strftime("%Y-%m") produces a year-month label. Keep an invalid-date count so your monthly report documents what it excluded.',
        'df["date"] = pd.to_datetime(df["date"], errors="coerce")\ndf["month"] = df["date"].dt.strftime("%Y-%m")',
        ['Parse `date`, count invalid dates in `rejected`, and exclude those rows.', 'Build `monthly` with `month` and `total` (monthly revenue totals), sorted by `month`.', 'Use `YYYY-MM` month labels.'],
        'import pandas as pd\ndf = pd.DataFrame({"date": ["2026-02-01", "2026-01-10", "bad", "2026-01-20"], "revenue": [30, 10, 999, 20]})\n',
        'import pandas as pd\ndf = pd.DataFrame({"date": ["2026-02-01", "2026-01-10", "bad", "2026-01-20"], "revenue": [30, 10, 999, 20]})\ndf["date"] = pd.to_datetime(df["date"], errors="coerce")\nrejected = int(df["date"].isna().sum())\ndf = df.dropna(subset=["date"]).copy()\ndf["month"] = df["date"].dt.strftime("%Y-%m")\nmonthly = df.groupby("month").agg(total=("revenue", "sum")).reset_index().sort_values("month").reset_index(drop=True)',
        [('Track rejected dates', 'assert rejected == 1'), ('Group valid records by month', 'assert monthly.to_dict("records") == [{"month": "2026-01", "total": 30}, {"month": "2026-02", "total": 30}]')],
        ['Convert before using .dt.', 'Count missing dates before dropping them.', 'Group the resulting month labels and sum revenue.'],
        'The invalid date’s large revenue does not enter a guessed month. The report explicitly counts its exclusion.',
        ['Parsing separates valid dates from invalid text.', '.dt exposes date operations.', 'Year-month labels sort chronologically in this format.'], 'Grouping only by month number combines different years.', kind='checkpoint', minutes=22)

    add('automation', 'paths', 'recursive', 'Choose the scope of a file search',
        'glob searches a pattern within a directory, while rglob searches recursively through its descendants. Recursive searches can include much more than you intended, so choose the scope explicitly. This exercise uses a generated practice folder with nested inputs. Return relative paths for a portable report and sort them so repeated runs have a predictable display order.',
        'from pathlib import Path\npaths = sorted(path.as_posix() for path in Path("inbox").rglob("*.csv"))',
        ['Set `direct` to sorted paths of direct `.csv` files inside `inbox`.', 'Set `recursive` to sorted paths of `.csv` files at any depth inside `inbox`.', 'Use forward slashes in returned path strings.'],
        'from pathlib import Path\n',
        'from pathlib import Path\ndirect = sorted(p.as_posix() for p in Path("inbox").glob("*.csv") if p.is_file())\nrecursive = sorted(p.as_posix() for p in Path("inbox").rglob("*.csv") if p.is_file())',
        [('Limit the direct search', 'assert direct == ["inbox/a.csv"]'), ('Include nested matches recursively', 'assert recursive == ["inbox/a.csv", "inbox/archive/b.csv"]')],
        ['glob operates at the selected level.', 'rglob includes descendants.', 'Use as_posix() before sorting the path strings.'],
        'The difference is scope, not just convenience. Choosing recursion deliberately reduces surprises in scripts that later process matching files.',
        ['Path anchors the search in one folder.', 'The pattern chooses matching names.', 'rglob includes nested folders.'], 'A recursive pattern can find old exports and backups along with current input files.', files={'inbox/a.csv':'x\n1\n','inbox/archive/b.csv':'x\n2\n','inbox/readme.txt':'notes'})
    add('automation', 'paths', 'hashes', 'Compare file contents',
        'Different filenames can contain the same data, while identical names in different folders can contain different data. A content hash summarises bytes so you can compare file contents independently of names. hashlib.sha256 produces a deterministic digest. Read in binary mode or use Path.read_bytes so text encoding and newline conversion do not alter what you compare.',
        'from hashlib import sha256\ndigest = sha256(b"hello").hexdigest()\nprint(len(digest))  # 64',
        ['Write `same_content(first, second)`, comparing SHA-256 hashes of the two files.', 'Return `True` for identical bytes and `False` for different bytes.'],
        'from pathlib import Path\nfrom hashlib import sha256\n\ndef same_content(first, second):\n    pass\n',
        'from pathlib import Path\nfrom hashlib import sha256\n\ndef same_content(first, second):\n    return sha256(Path(first).read_bytes()).digest() == sha256(Path(second).read_bytes()).digest()',
        [('Match equal content under different names', 'assert same_content("one.txt", "copy.txt") is True'), ('Distinguish changed content', 'assert same_content("one.txt", "changed.txt") is False'), ('Compare a file with itself', 'assert same_content("one.txt", "one.txt") is True')],
        ['Read both files as bytes.', 'Hash each byte sequence with sha256().', 'Compare the digests, not the hash objects.'],
        'Content checks are useful for duplicate detection and verifying a copy. For very large files, stream chunks instead of reading everything at once.',
        ['b"hello" is a byte string.', 'sha256 consumes bytes.', 'hexdigest presents the digest as hexadecimal text.'], 'A hash object is not the digest; call digest() or hexdigest() before comparing.', files={'one.txt':'same content','copy.txt':'same content','changed.txt':'different content'})
    add('automation', 'dates', 'date-window', 'Calculate a date window',
        'timedelta represents a duration that can be added to or subtracted from a date. It handles month boundaries and leap years for you. To describe a seven-day reporting window including an end date, subtract six days for the start. Counting both endpoints is different from measuring the duration between them, so state your convention.',
        'from datetime import date, timedelta\nend = date(2026, 3, 2)\nstart = end - timedelta(days=2)\nprint(start)  # 2026-02-28',
        ['Write `week_window(end_text)`, accepting `YYYY-MM-DD`.', 'Return a tuple of start and end strings for a seven-day inclusive window.', 'Use `date.fromisoformat` and `timedelta`.'],
        'from datetime import date, timedelta\n\ndef week_window(end_text):\n    pass\n',
        'from datetime import date, timedelta\n\ndef week_window(end_text):\n    end = date.fromisoformat(end_text)\n    start = end - timedelta(days=6)\n    return start.isoformat(), end.isoformat()',
        [('Cross a month boundary', 'assert week_window("2026-03-03") == ("2026-02-25", "2026-03-03")'), ('Handle a leap-year boundary', 'assert week_window("2024-03-01") == ("2024-02-24", "2024-03-01")')],
        ['An inclusive seven-day window begins six days before the end.', 'Subtract timedelta(days=6).', 'Use isoformat() to return YYYY-MM-DD strings.'],
        'Calendar arithmetic is delegated to the date library. Manual day-number subtraction would fail at month boundaries.',
        ['A date is a calendar value.', 'A timedelta is a duration.', 'Subtracting the duration handles the calendar transition.'], 'Subtracting seven days would create eight included dates if both endpoints are counted.')
    add('automation', 'dates', 'regex-extract', 'Extract a structured identifier',
        'A regular expression describes a text pattern. re.findall returns non-overlapping matches; parentheses select which part of each match is returned. Use raw Python strings for regex patterns so backslashes remain easy to read. Start with a narrow pattern that matches the identifier format you expect, and test it against near-matches that should be excluded.',
        'import re\nids = re.findall(r"INV-(\\d{3})(?!\\d)", "INV-104 INV-205")\nprint(ids)  # ["104", "205"]',
        ['Extract exactly three-digit IDs following `INV-` into `invoice_ids`.', 'Do not accept the first three digits of a longer ID.', 'Keep IDs as strings so leading zeros survive.'],
        'import re\ntext = "Paid INV-007; pending INV-120; ignore INV-12 and INV-1234."\n',
        'import re\ntext = "Paid INV-007; pending INV-120; ignore INV-12 and INV-1234."\ninvoice_ids = re.findall(r"INV-(\\d{3})(?!\\d)", text)',
        [('Extract exact-length identifiers', 'assert invoice_ids == ["007", "120"]')],
        ['\\d matches a digit and {3} requires three of them.', 'Capture the digits in parentheses.', '(?!\\d) prevents another digit immediately after the match.'],
        'Keeping IDs as text preserves 007. Numeric conversion would change an identifier’s representation without helping the task.',
        ['INV- matches the literal prefix.', 'The group captures exactly three digits.', 'The negative lookahead rejects a following digit.'], 'A digit pattern without a boundary may extract part of a longer identifier.')
    add('automation', 'dates', 'regex-clean', 'Normalise repeated whitespace',
        'Repeated spaces, tabs, and newlines can make equivalent labels compare differently. re.sub(pattern, replacement, text) replaces matching regions. The pattern \\s+ matches one or more whitespace characters. Strip the result to remove the single spaces that may remain at the ends. This is useful for ordinary labels, but preserve whitespace when it has meaning in source code or formatted documents.',
        'import re\nprint(re.sub(r"\\s+", " ", "A   B").strip())  # A B',
        ['Write `clean_label(text)`, replacing whitespace runs with one space.', 'Strip the result and lowercase it.'],
        'import re\n\ndef clean_label(text):\n    pass\n',
        'import re\n\ndef clean_label(text):\n    return re.sub(r"\\s+", " ", text).strip().lower()',
        [('Normalise spaces, tabs, and newlines', 'assert clean_label("  MONTHLY\\t Sales\\nReport ") == "monthly sales report"'), ('Handle blank and ordinary input', 'assert clean_label(" \\t ") == "" and clean_label("Tea") == "tea"')],
        ['Use re.sub with a raw pattern.', 'Replace each whitespace run with one ordinary space.', 'Then strip and lowercase the result.'],
        'Normalising whitespace produces comparable labels while preserving word boundaries.',
        ['The + combines a whole run into one match.', 'The replacement inserts one space per run.', 'strip removes outer whitespace after substitution.'], 'Removing all whitespace would join neighbouring words into one string.')
    add('automation', 'copy', 'log-summary', 'Report what an automation did',
        'An automation should return enough information to explain its work. A list of events can be summarised by status, including zero counts for statuses that did not occur. Starting with an explicit result schema keeps reports comparable between runs. An unknown status should be detected rather than silently counted as success.',
        'summary = {"copied": 0, "skipped": 0, "failed": 0}\nsummary["copied"] += 1',
        ['Write `count_events(events)`, counting `status` values `"copied"`, `"skipped"`, and `"failed"`.', 'Always return all three keys. Raise `ValueError` for any unknown `status`.'],
        'def count_events(events):\n    pass\n',
        'def count_events(events):\n    summary = {"copied": 0, "skipped": 0, "failed": 0}\n    for event in events:\n        status = event["status"]\n        if status not in summary:\n            raise ValueError("unknown status")\n        summary[status] += 1\n    return summary',
        [('Count each outcome', 'assert count_events([{"status": "copied"}, {"status": "failed"}, {"status": "copied"}]) == {"copied": 2, "skipped": 0, "failed": 1}'), ('Keep an empty-run schema', 'assert count_events([]) == {"copied": 0, "skipped": 0, "failed": 0}'), ('Reject unknown statuses', 'try:\n    count_events([{"status": "maybe"}])\nexcept ValueError:\n    pass\nelse:\n    raise AssertionError()')],
        ['Initialise the result with all three keys.', 'Validate the status before incrementing.', 'Use the status string as the dictionary key.'],
        'Explicit outcome counts make a script easier to trust and troubleshoot. A successful process exit alone does not tell you which files were handled.',
        ['The schema is stable across runs.', 'An event updates one category.', 'Zero remains meaningful for categories without events.'], 'Treating unknown statuses as success can hide failures.')
    add('automation', 'copy', 'collisions', 'Detect a collision before copying',
        'Two source files may map to the same destination after a naming rule is applied. A dry-run plan should detect that conflict before file operations begin. Group sources by destination and report destinations with more than one source. This exercise works entirely with path strings, so it can inspect a plan without creating or changing any files.',
        'sources_by_target = {}\nsources_by_target.setdefault("out/a.txt", []).append("in/a.txt")',
        ['Write `collisions(plan)`, returning a sorted list of `destination` strings used by more than one `plan` entry.', 'An empty or conflict-free `plan` should return an empty list.'],
        'def collisions(plan):\n    pass\n',
        'def collisions(plan):\n    counts = {}\n    for item in plan:\n        destination = item["destination"]\n        counts[destination] = counts.get(destination, 0) + 1\n    return sorted(destination for destination, count in counts.items() if count > 1)',
        [('Find repeated destinations once each', 'assert collisions([{"destination": "b"}, {"destination": "a"}, {"destination": "b"}, {"destination": "a"}]) == ["a", "b"]'), ('Handle conflict-free and empty plans', 'assert collisions([{"destination": "x"}, {"destination": "y"}]) == [] and collisions([]) == []')],
        ['Build destination frequencies.', 'Keep destinations whose count exceeds one.', 'Sort the destination names before returning them.'],
        'The conflict report lets a person choose a naming rule before data is copied. This practice compares exact strings; real filesystem rules can also involve case and path normalisation.',
        ['setdefault creates a group the first time it is needed.', 'append records one source under the destination.', 'Multiple sources under one key indicate a conflict.'], 'Different path strings can refer to the same file on a real filesystem; production conflict checks need appropriate path normalisation.')
    add('automation', 'copy', 'manifest-review', 'Checkpoint · audit a folder',
        'Create a small manifest describing an input folder before processing it. A manifest records what was present, making later comparisons possible. For this exercise, inspect only direct files and record each filename, byte size, and SHA-256 digest. Sort by filename and write JSON. The output is checked before the disposable practice folder is removed.',
        'record = {"name": path.name, "bytes": len(data), "sha256": sha256(data).hexdigest()}',
        ['Build `manifest` for direct files in `inbox`, sorted by name.', 'Each record needs `name`, `bytes`, and `sha256`.', 'Save the list to `manifest.json`. Ignore subdirectories.'],
        'from pathlib import Path\nfrom hashlib import sha256\nimport json\n',
        'from pathlib import Path\nfrom hashlib import sha256\nimport json\nmanifest = []\nfor path in sorted(Path("inbox").iterdir(), key=lambda p: p.name):\n    if path.is_file():\n        data = path.read_bytes()\n        manifest.append({"name": path.name, "bytes": len(data), "sha256": sha256(data).hexdigest()})\nwith open("manifest.json", "w", encoding="utf-8") as file:\n    json.dump(manifest, file, indent=2)',
        [('Inspect direct files in order', 'assert [r["name"] for r in manifest] == ["a.txt", "b.txt"] and [r["bytes"] for r in manifest] == [3, 5]'), ('Calculate content digests', 'from hashlib import sha256\nassert [r["sha256"] for r in manifest] == [sha256(b"abc").hexdigest(), sha256(b"hello").hexdigest()]'), ('Save valid manifest JSON', 'import json\nassert json.load(open("manifest.json", encoding="utf-8")) == manifest')],
        ['List direct children and keep files only.', 'Read each file once as bytes and use the bytes for both measurements.', 'Write the complete list with json.dump.'],
        'The manifest combines file discovery, content inspection, and structured output. A later run could compare hashes to find which files changed.',
        ['name identifies the file in the chosen folder.', 'len(data) measures bytes, not text characters.', 'The digest fingerprints the exact content.'], 'Text character count and byte size differ for many non-ASCII characters.', kind='checkpoint', minutes=25, files={'inbox/a.txt':'abc','inbox/b.txt':'hello','inbox/nested/ignore.txt':'ignore'})

    add('web', 'html', 'html-list', 'Render a list without exposing markup',
        'HTML uses ul for an unordered list and li for each item. Build the wrapper once and generate one escaped item per input string. Keep data escaping separate from the tags you intentionally create. An empty input can still produce a valid empty list container, giving the caller a consistent output shape.',
        'from html import escape\nitems = "".join(f"<li>{escape(name)}</li>" for name in names)\npage = f"<ul>{items}</ul>"',
        ['Write `render_list(names)`, returning a `ul` containing one `li` per name.', 'Escape every name, preserve order, and insert no extra whitespace.', 'For an empty list, return `"<ul></ul>"`.'],
        'from html import escape\n\ndef render_list(names):\n    pass\n',
        'from html import escape\n\ndef render_list(names):\n    items = "".join(f"<li>{escape(name)}</li>" for name in names)\n    return f"<ul>{items}</ul>"',
        [('Render items in order', 'assert render_list(["Tea", "Cake"]) == "<ul><li>Tea</li><li>Cake</li></ul>"'), ('Escape inserted text', 'assert render_list(["A&B", "<b>"]) == "<ul><li>A&amp;B</li><li>&lt;b&gt;</li></ul>"'), ('Handle empty input', 'assert render_list([]) == "<ul></ul>"')],
        ['Generate and join the li fragments first.', 'Escape each name, not the complete HTML fragment.', 'Wrap the joined items in ul tags.'],
        'The output has predictable structure for zero, one, or many items. User text cannot turn into new tags.',
        ['Each string becomes one list item.', 'join combines the fragments without extra separators.', 'The outer wrapper is added once.'], 'Escaping the whole completed fragment would display its tags as text instead of creating a list.')
    add('web', 'html', 'attributes', 'Escape a value inside an attribute',
        'Text can appear inside an HTML attribute as well as between tags. Quoted attributes need quote characters escaped too. html.escape(value, quote=True) handles ampersands, angle brackets, and quotes. Always keep the attribute value quoted. This exercise generates a text input; it does not submit a form or contact another service.',
        'from html import escape\nfield = f\'<input value="{escape(text, quote=True)}">\'',
        ['Write `input_field(text)`, returning `<input type="text" value="...">`.', 'Escape the inserted value including quotes.'],
        'from html import escape\n\ndef input_field(text):\n    pass\n',
        'from html import escape\n\ndef input_field(text):\n    return f\'<input type="text" value="{escape(text, quote=True)}">\'',
        [('Render ordinary values', 'assert input_field("Tea") == \'<input type="text" value="Tea">\''), ('Keep quotes and markup inside the value', 'assert input_field(\'A" & <B>\') == \'<input type="text" value="A&quot; &amp; &lt;B&gt;">\'')],
        ['Use escape(text, quote=True).', 'Place the result inside double quotes in the HTML attribute.', 'Use a single-quoted Python f-string to keep the quoting readable.'],
        'Attribute context needs quote escaping. The generated markup keeps the entire input string as one value.',
        ['The Python string wraps the HTML fragment.', 'The HTML value is quoted independently.', 'Escaping protects that inner boundary.'], 'Escaping text is not URL validation; links and other special contexts need their own rules.')
    add('web', 'query', 'encode', 'Build a query string correctly',
        'urlencode turns a mapping into a query string and escapes special characters in its values. An ampersand inside a value must not become a parameter separator. Encoding and parsing are complementary operations: encode values to construct a URL, then parse them to recover the original data. Avoid assembling query strings by concatenating raw user text.',
        'from urllib.parse import urlencode\nprint(urlencode({"q": "tea & cake"}))  # q=tea+%26+cake',
        ['Write `search_url(term)`, returning `"/search?"` plus an encoded `q` parameter.', 'It must preserve spaces, ampersands, and non-ASCII characters when parsed.'],
        'from urllib.parse import urlencode\n\ndef search_url(term):\n    pass\n',
        'from urllib.parse import urlencode\n\ndef search_url(term):\n    return "/search?" + urlencode({"q": term})',
        [('Create the search route', 'assert search_url("tea").startswith("/search?")'), ('Round-trip special characters', 'from urllib.parse import urlsplit, parse_qs\nfor term in ["tea & cake", "café", "a=b?c"]:\n    assert parse_qs(urlsplit(search_url(term)).query) == {"q": [term]}')],
        ['Put the raw term in a dictionary under q.', 'Pass that dictionary to urlencode.', 'Prefix the result with /search?.'],
        'Parsing the generated URL verifies the value’s meaning rather than requiring one particular spelling of escaped spaces.',
        ['q is the parameter name.', 'The ampersand is encoded as data.', 'The parser can later recover the original phrase.'], 'Replacing spaces alone is not enough to encode arbitrary query values.')
    add('web', 'query', 'url-parts', 'Separate a path from its query',
        'A URL contains several components. urlsplit separates its scheme, network location, path, query, and fragment. A route usually compares the path without the query string. If you compare the entire URL, adding a harmless query parameter can make an existing route look missing. Parse first, then handle each component according to its role.',
        'from urllib.parse import urlsplit\nparts = urlsplit("/report?region=North#totals")\nprint(parts.path)   # /report\nprint(parts.query)  # region=North',
        ['Write `report_request(url)`, returning a dictionary with `path` and `region`.', 'Use the first `region` query value, defaulting to `"all"` when missing or blank.', 'Ignore the fragment.'],
        'from urllib.parse import urlsplit, parse_qs\n\ndef report_request(url):\n    pass\n',
        'from urllib.parse import urlsplit, parse_qs\n\ndef report_request(url):\n    parts = urlsplit(url)\n    params = parse_qs(parts.query)\n    return {"path": parts.path, "region": params.get("region", ["all"])[0]}',
        [('Separate route and query', 'assert report_request("/report?region=North#totals") == {"path": "/report", "region": "North"}'), ('Handle an absolute URL and encoded value', 'assert report_request("https://example.invalid/report?region=New+York") == {"path": "/report", "region": "New York"}'), ('Default missing input', 'assert report_request("/report") == {"path": "/report", "region": "all"}')],
        ['Start with urlsplit(url).', 'Pass only parts.query to parse_qs.', 'Read parts.path and the first region value.'],
        'Parsing separates routing from filtering. The fragment is a browser-side location marker and is not part of the HTTP request target sent to a server.',
        ['path identifies the route.', 'query carries parameter text.', 'fragment is separate from both.'], 'Do not split a whole URL on ? and assume the remainder contains only query parameters.')
    add('web', 'responses', 'method', 'Distinguish the method from the path',
        'An HTTP request has a method as well as a path. GET commonly retrieves a representation; POST commonly submits data for processing. A route can exist while rejecting a particular method. Here model that distinction with numeric status codes: 200 for an accepted GET, 405 for another method on the known route, and 404 for an unknown path.',
        'if path == "/status" and method == "GET":\n    status = 200',
        ['Write `route_status(method, path)`. The only route is `/status` and its only supported method is `GET`.', 'Return 404 for unknown paths, 405 for unsupported methods on `/status`, and 200 for `GET` `/status`.'],
        'def route_status(method, path):\n    pass\n',
        'def route_status(method, path):\n    if path != "/status":\n        return 404\n    if method != "GET":\n        return 405\n    return 200',
        [('Accept the supported request', 'assert route_status("GET", "/status") == 200'), ('Distinguish an unsupported method', 'assert route_status("POST", "/status") == 405'), ('Prioritise unknown paths', 'assert route_status("GET", "/missing") == 404 and route_status("POST", "/missing") == 404')],
        ['Check whether the path exists first.', 'Then check the method for the known route.', 'Return 200 only after both checks pass.'],
        'The response explains whether the client chose an unknown resource or an unsupported action on a known one.',
        ['The path and method are independent request properties.', 'Both must match for the success case.', 'Separate branches communicate separate failure reasons.'], 'This exercise models routing only; it does not start or expose a server.')
    add('web', 'responses', 'payload', 'Validate a JSON request body',
        'Parsing valid JSON only proves that its syntax is correct. An application still needs to check whether the parsed value has the expected structure. JSON may contain a list or number where you expected a dictionary. Validate the outer type, required fields, and field types before using them. Here a name must be nonblank text after stripping.',
        'data = json.loads(body)\nif not isinstance(data, dict):\n    raise ValueError("expected an object")',
        ['Write `parse_name(body)`, returning the stripped `name` from a JSON object.', 'Raise `ValueError` for malformed JSON, a non-object value, or a missing, non-string, or blank `name`.'],
        'import json\n\ndef parse_name(body):\n    pass\n',
        'import json\n\ndef parse_name(body):\n    data = json.loads(body)\n    if not isinstance(data, dict):\n        raise ValueError("expected an object")\n    name = data.get("name")\n    if not isinstance(name, str) or not name.strip():\n        raise ValueError("name must be nonblank text")\n    return name.strip()',
        [('Parse valid input', 'assert parse_name(\'{"name": " Ari "}\') == "Ari"'), ('Reject invalid structures and values', 'for body in ["bad", "[]", "null", "{}", \'{"name": 4}\', \'{"name": "  "}\']:\n    try:\n        parse_name(body)\n    except ValueError:\n        pass\n    else:\n        raise AssertionError()')],
        ['JSONDecodeError from json.loads is a subclass of ValueError.', 'Validate the dictionary before calling get.', 'Use isinstance(name, str) before calling strip.'],
        'Validation converts many malformed inputs into one clear error contract. Downstream code can then rely on receiving a usable name.',
        ['JSON parsing creates Python values.', 'The outer structure is checked separately.', 'Field validation comes after the structure check.'], 'Calling strip on an unvalidated numeric value raises a different error and skips your intended input policy.')
    add('web', 'responses', 'api-filter', 'Filter records for an API response',
        'A query parameter should change which records are returned, not the original dataset. A pure filtering function is easy to test before connecting it to HTTP. In this exercise, the special region "all" selects every record. Return a new list in input order. The records themselves are only read; the function does not mutate their fields.',
        'selected = [row for row in rows if row["region"] == region]',
        ['Write `filter_sales(rows, region="all")`, returning matching records.', 'For `"all"`, return every record in a new list. For no matches, return an empty list.', 'Keep the input unchanged.'],
        'def filter_sales(rows, region="all"):\n    pass\n',
        'def filter_sales(rows, region="all"):\n    return [row for row in rows if region == "all" or row["region"] == region]',
        [('Filter while retaining order', 'data = [{"region": "North", "value": 2}, {"region": "South", "value": 3}, {"region": "North", "value": 4}]\nassert filter_sales(data, "North") == [data[0], data[2]]'), ('Return a new full list by default', 'assert filter_sales(data) == data and filter_sales(data) is not data'), ('Handle absent and empty results', 'assert filter_sales(data, "West") == [] and filter_sales([]) == [] and len(data) == 3')],
        ['Accept a row if the requested region is all or matches the row.', 'A comprehension naturally creates a new list.', 'Do not remove items from the input while iterating.'],
        'The filter can be reused behind an API or in a local report. Keeping data selection separate from response formatting makes both easier to test.',
        ['The condition chooses included records.', 'The list comprehension preserves iteration order.', 'Unmatched input produces an empty list.'], 'An empty result is often a valid answer, not a server error.')
    add('web', 'responses', 'api-review', 'Checkpoint · a queryable sales summary',
        'Combine URL parsing, filtering, and JSON output into a small response function. This is a local model of an API, so no connection or deployment is needed. The requested region selects data, and the body reports its record count and total revenue. An unknown region should produce a valid zero-count summary rather than an invented record.',
        'body = json.dumps({"region": "North", "count": 2, "total": 30})',
        ['Write `summary_response(query, rows)`. Read the first `region` value, defaulting to `"all"`.', 'Return a dictionary with `status=200` and a JSON string `body` containing `region`, `count`, and `total`.', 'Use exact `region` matching and preserve the source `rows`.'],
        'import json\nfrom urllib.parse import parse_qs\n\ndef summary_response(query, rows):\n    pass\n',
        'import json\nfrom urllib.parse import parse_qs\n\ndef summary_response(query, rows):\n    region = parse_qs(query).get("region", ["all"])[0]\n    selected = [row for row in rows if region == "all" or row["region"] == region]\n    data = {"region": region, "count": len(selected), "total": sum(row["revenue"] for row in selected)}\n    return {"status": 200, "body": json.dumps(data)}',
        [('Filter and summarise the request', 'import json\nrows = [{"region": "North", "revenue": 10}, {"region": "South", "revenue": 30}, {"region": "North", "revenue": 20}]\nr = summary_response("region=North", rows)\nassert r["status"] == 200 and json.loads(r["body"]) == {"region": "North", "count": 2, "total": 30}'), ('Default to all records', 'assert json.loads(summary_response("", rows)["body"]) == {"region": "all", "count": 3, "total": 60}'), ('Handle a region without records', 'assert json.loads(summary_response("region=West", rows)["body"]) == {"region": "West", "count": 0, "total": 0} and len(rows) == 3')],
        ['Parse the query and select the first region value.', 'Build a list of matching records, then calculate its count and total.', 'Serialise the summary with json.dumps and return it with status 200.'],
        'You have connected a request parameter to a computed response. The same components can later be placed inside a real web framework.',
        ['The payload is a dictionary of meaningful fields.', 'json.dumps converts it into a transportable string.', 'A client can decode the body and display the result.'], 'Returning a Python dictionary inside body is different from returning JSON text.', kind='checkpoint', minutes=25)
