"""Original function, file, analysis, pandas, automation, and web practice."""


def add_practice(add):
    add('functions', 'return', 'print-return', 'Repair print versus return',
        'A function that reaches its end without return produces None. Printing inside the function may look correct in the console, but the caller still receives None. Separate calculation from display: return the calculated value, then let the caller decide whether to print, save, or use it in another calculation. This separation is what makes functions reusable.',
        'def double(n):\n    return n * 2\n\nresult = double(3)\nprint(result + 1)  # 7',
        ['Repair `tax(amount)` so it returns 6% of `amount` rather than only printing it.', 'It should return a numeric value for any nonnegative `amount`.'],
        'def tax(amount):\n    print(amount * 0.06)\n',
        'def tax(amount):\n    return amount * 0.06',
        [('Return a reusable value', 'assert tax(100) == 6'), ('Handle a different amount and zero', 'assert tax(50) == 3 and tax(0) == 0')],
        ['The problem is how the result leaves the function.', 'The caller needs a value it can calculate with.', 'Replace print(...) with return followed by the expression.'],
        'Returning allows the caller to write amount + tax(amount). Console output alone cannot be used that way.',
        ['double computes a value.', 'return hands it to the caller.', 'The caller can then perform another calculation.'], 'Seeing the right text in the console does not prove that the function returned the right value.', kind='debug')
    add('functions', 'defaults', 'keywords', 'Make arguments readable',
        'Positional arguments are matched by order. Keyword arguments explicitly name the parameter they belong to. Named arguments make calls easier to review when several inputs have the same type. They also let you skip a default parameter while changing a later one. Keep positional arguments before keyword arguments in an ordinary call.',
        'def label(name, prefix="Hello", suffix="!"):\n    return f"{prefix} {name}{suffix}"\nprint(label("Ari", suffix="."))  # Hello Ari.',
        ['Using the supplied `shipping` function, set `express_total` for a `basket` of 40, `fee` 12, and `discount` 5.', 'Set `standard_total` for a `basket` of 40 with `discount` 5 and the default `fee`.', 'Use keyword arguments for `fee` and `discount`.'],
        'def shipping(basket, fee=4, discount=0):\n    return basket + fee - discount\n\n',
        'def shipping(basket, fee=4, discount=0):\n    return basket + fee - discount\n\nexpress_total = shipping(40, fee=12, discount=5)\nstandard_total = shipping(40, discount=5)',
        [('Override both optional values', 'assert express_total == 47'), ('Keep the default fee', 'assert standard_total == 39')],
        ['Supply the basket value first.', 'Name fee=12 and discount=5 in the express call.', 'Leave fee out of the standard call.'],
        'Named arguments communicate intent at the call site. They are especially helpful for functions with several optional settings.',
        ['name is supplied positionally.', 'suffix is supplied by name.', 'prefix uses its default because it was omitted.'], 'Swapping two numeric positional arguments may run successfully but produce the wrong answer.')
    add('functions', 'return', 'scope', 'Keep each call independent',
        'Variables assigned inside a function normally belong to that function call. Initialising an accumulator inside the function gives every call a fresh start. A global accumulator can accidentally leak results from one call to the next. A good test therefore calls the same function more than once, rather than checking only its first answer.',
        'def count(values):\n    total = 0\n    for value in values:\n        total += 1\n    return total',
        ['Write `add_values(values)`, returning the sum using a local accumulator.', 'Repeated calls must not include results from earlier calls. Return 0 for an empty list.'],
        'def add_values(values):\n    pass\n',
        'def add_values(values):\n    total = 0\n    for value in values:\n        total += value\n    return total',
        [('Add the first input', 'assert add_values([2, 3]) == 5'), ('Start fresh on later calls', 'assert add_values([10]) == 10 and add_values([2, 3]) == 5'), ('Handle empty input', 'assert add_values([]) == 0')],
        ['Initialise total inside the function but before the loop.', 'Update it for each input value.', 'Return it after the loop.'],
        'A local accumulator makes the function independent of prior calls. Independence simplifies testing and reuse.',
        ['The assignment runs once per function call.', 'The loop updates only that call’s local state.', 'return sends the completed result back.'], 'Returning inside the loop stops after the first item.')
    add('functions', 'validation', 'guards', 'Use an early return for an edge case',
        'A guard clause handles an exceptional or empty case at the top of a function. The ordinary calculation can then remain at the outer indentation level. This is useful when division would fail on empty input. Decide what empty input means before writing the formula; here it means no average is available, represented by None.',
        'def first(values):\n    if not values:\n        return None\n    return values[0]',
        ['Write `average_price(prices)`. Return `None` for an empty list.', 'Otherwise return the average rounded to two decimals. Include zero `prices`.'],
        'def average_price(prices):\n    pass\n',
        'def average_price(prices):\n    if not prices:\n        return None\n    return round(sum(prices) / len(prices), 2)',
        [('Handle an empty list', 'assert average_price([]) is None'), ('Calculate and round', 'assert average_price([10, 11, 11]) == 10.67'), ('Keep zeros', 'assert average_price([0, 10]) == 5')],
        ['Check if not prices before dividing.', 'Return None immediately for that case.', 'Calculate sum(prices) / len(prices) otherwise.'],
        'The guard prevents division by zero and makes the empty-input policy explicit to the caller.',
        ['An empty list is false in a condition.', 'The guard exits before any indexing.', 'Nonempty input reaches the ordinary path.'], 'Returning zero for no observations can be misleading when zero is also a valid measurement.')
    add('functions', 'defaults', 'tuples', 'Return more than one result',
        'A function can return a tuple of related values. Write return first, second and unpack the result into two names at the call site. A tuple is ordered, so the producer and caller must agree on which position means what. Use a dictionary instead when many named results would be easier to understand.',
        'def bounds(values):\n    return min(values), max(values)\n\nlow, high = bounds([3, 9, 5])',
        ['Write `split_minutes(total)`, returning a tuple of whole hours and leftover minutes.', 'Use floor division and remainder. Inputs are nonnegative integers.'],
        'def split_minutes(total):\n    pass\n',
        'def split_minutes(total):\n    return total // 60, total % 60',
        [('Split a duration', 'assert split_minutes(135) == (2, 15)'), ('Handle exact hours and zero', 'assert split_minutes(120) == (2, 0) and split_minutes(0) == (0, 0)'), ('Handle less than an hour', 'assert split_minutes(59) == (0, 59)')],
        ['Count whole groups of 60.', 'The remainder is the leftover minutes.', 'Return the two expressions separated by a comma.'],
        'Unpacking lets a caller write hours, minutes = split_minutes(135). The function returns data instead of imposing a display format.',
        ['The function returns two ordered values.', 'The caller unpacks them in the same order.', 'The names low and high explain the positions.'], 'Reversing the tuple order changes its meaning even if both values are individually correct.')
    add('functions', 'validation', 'compose', 'Build one function from another',
        'A small function can call another function instead of repeating its logic. This is composition: combine reliable pieces into a larger operation. In the example, normalisation has one responsibility and greeting has another. If the cleaning rule changes, there is only one place to update it. The caller should not have to know the internal steps.',
        'def clean(text):\n    return text.strip().title()\n\ndef greeting(text):\n    return f"Hello {clean(text)}"',
        ['Write `invoice_total(prices)` using the supplied `subtotal` and `add_tax` functions.', 'Return the sum after the 6% tax, rounded to two decimals.'],
        'def subtotal(prices):\n    return sum(prices)\n\ndef add_tax(amount):\n    return amount * 1.06\n\ndef invoice_total(prices):\n    pass\n',
        'def subtotal(prices):\n    return sum(prices)\n\ndef add_tax(amount):\n    return amount * 1.06\n\ndef invoice_total(prices):\n    return round(add_tax(subtotal(prices)), 2)',
        [('Compose the calculation', 'assert invoice_total([10, 20]) == 31.8'), ('Round at the end', 'assert invoice_total([9.99, 3.5]) == 14.3'), ('Handle an empty basket', 'assert invoice_total([]) == 0')],
        ['Start by calling subtotal(prices).', 'Pass that result into add_tax().', 'Round the final result, then return it.'],
        'Composition separates addition, tax, and final formatting. Each part can be reasoned about and tested independently.',
        ['clean returns a normalised name.', 'greeting uses that returned value.', 'Neither function needs duplicated cleaning code.'], 'Passing the function name without parentheses passes the function itself, not the result of calling it.')
    add('functions', 'validation', 'raise', 'Reject a value with a clear error',
        'Sometimes invalid input should stop a calculation rather than produce None. raise ValueError(message) communicates that a value is outside the accepted range. Choose a message that identifies the rule. Callers may handle the error with try/except. Here the function accepts a fraction between zero and one inclusive and rejects values outside that range.',
        'def positive(value):\n    if value < 0:\n        raise ValueError("value must be nonnegative")\n    return value',
        ['Write `as_percent(fraction)`, returning `fraction` * 100.', 'Raise `ValueError` with a nonempty message for fractions below 0 or above 1.'],
        'def as_percent(fraction):\n    pass\n',
        'def as_percent(fraction):\n    if fraction < 0 or fraction > 1:\n        raise ValueError("fraction must be between 0 and 1")\n    return fraction * 100',
        [('Convert a valid fraction', 'assert as_percent(0.25) == 25'), ('Accept both boundaries', 'assert as_percent(0) == 0 and as_percent(1) == 100'), ('Reject both invalid directions', 'for value in [-0.1, 1.1]:\n    try:\n        as_percent(value)\n    except ValueError as error:\n        assert str(error)\n    else:\n        raise AssertionError()')],
        ['Check both sides of the accepted interval.', 'Use or between the invalid conditions.', 'Raise before returning the percentage.'],
        'The function protects its assumptions. Returning a plausible-looking percentage for invalid input would conceal the problem.',
        ['The guard checks the rule.', 'raise stops normal execution.', 'A valid value reaches return.'], 'Use > 1 rather than >= 1 because a fraction of exactly one is valid.')
    add('functions', 'validation', 'clean-review', 'Checkpoint · reusable name cleaning',
        'Write a function that another script could safely reuse. It should normalise labels, discard blanks, and remove duplicates while preserving first appearance. Different calls must not share state. This combines text methods, lists, sets, conditions, and function return values. Think through empty input and differently capitalised duplicates before writing the main loop.',
        'seen = set()\nresult = []\n# Keep a value only the first time it appears.',
        ['Write `unique_names(names)`, stripping and lowercasing `names`.', 'Remove blanks and duplicates, preserving first occurrence order.', 'Do not modify the input list.'],
        'def unique_names(names):\n    pass\n',
        'def unique_names(names):\n    seen = set()\n    result = []\n    for name in names:\n        cleaned = name.strip().lower()\n        if cleaned and cleaned not in seen:\n            result.append(cleaned)\n            seen.add(cleaned)\n    return result',
        [('Normalise and deduplicate', 'assert unique_names([" Ari ", "BO", "ari", "", "  ", "Bo"]) == ["ari", "bo"]'), ('Handle empty and later calls', 'assert unique_names([]) == [] and unique_names(["X"]) == ["x"]'), ('Preserve the source', 'source = [" A ", "a"]\nassert unique_names(source) == ["a"] and source == [" A ", "a"]')],
        ['Create fresh result and seen containers inside the function.', 'Clean before checking membership.', 'Add a name to both containers only if it is nonblank and unseen.'],
        'The function now expresses one reusable cleaning policy. Its boundary and repeat-call checks are just as important as the main example.',
        ['The set supports membership checks.', 'The list preserves presentation order.', 'Both should start empty for each call.'], 'Converting directly to a set loses the required order.', kind='checkpoint', minutes=20)

    add('files', 'text', 'line-counts', 'Count useful lines',
        'Iterating over an open text file yields lines one at a time. This avoids loading the entire file when you only need a summary. Lines usually retain their trailing newline, so strip them before checking content. Decide whether blank lines count as records. Here they do not, but the raw line count still records every physical line.',
        'with open("sample.txt", encoding="utf-8") as file:\n    for line in file:\n        print(line.strip())',
        ['Read `log.txt` line by line.', 'Set `raw_count` to all lines and `useful_count` to nonblank lines.'],
        '# Count physical lines and nonblank lines separately.\n',
        'raw_count = 0\nuseful_count = 0\nwith open("log.txt", encoding="utf-8") as file:\n    for line in file:\n        raw_count += 1\n        if line.strip():\n            useful_count += 1',
        [('Count every physical line', 'assert raw_count == 5'), ('Exclude blank records', 'assert useful_count == 3')],
        ['Initialise two counters.', 'Increment raw_count for every iteration.', 'Increment useful_count only when line.strip() is nonempty.'],
        'Different counts answer different questions: file size in lines versus actual records. Keeping both can reveal empty records in an export.',
        ['The file object is iterable.', 'Each iteration produces one line.', 'strip removes the line ending and outer whitespace.'], 'A whitespace-only line is not empty until its whitespace is removed.', files={'log.txt':'start\n\nclean\n   \nfinish\n'})
    add('files', 'text', 'append', 'Add a line without replacing the file',
        'Opening a file with mode "w" truncates its existing contents. Mode "a" appends at the end. Neither mode automatically inserts a newline, so include one when writing a complete line. Before choosing a mode, decide whether the output should replace a report or add an entry to a log. Here you are adding a new event to an existing log.',
        'with open("events.txt", "a", encoding="utf-8") as file:\n    file.write("finished\\n")',
        ['Append `"exported"` as a new line to `events.txt`.', 'Preserve its two existing lines and leave a final newline.'],
        '# Append one event.\n',
        'with open("events.txt", "a", encoding="utf-8") as file:\n    file.write("exported\\n")',
        [('Preserve old events and append the new one', 'from pathlib import Path\nassert Path("events.txt").read_text(encoding="utf-8") == "loaded\\ncleaned\\nexported\\n"')],
        ['Use append mode, "a".', 'Write the event plus a newline character.', 'The Python string should be "exported\\n".'],
        'Appending is appropriate for a log, but repeated runs can add duplicate events. Later automation exercises will track repeated work explicitly.',
        ['Append mode preserves existing content.', 'write accepts exactly the text to add.', 'The newline separates this entry from the next one.'], 'Using "w" here would erase the earlier events.', files={'events.txt':'loaded\ncleaned\n'})
    add('files', 'csv', 'quoted', 'Read a comma inside a CSV field',
        'CSV quotes allow a field to contain a comma without creating an extra column. Splitting a line on commas does not understand those quotes. csv.DictReader does. This distinction matters for addresses, company names, and descriptive text. Inspect the sample file, then compare the logical fields with the commas you see in the raw text.',
        'import csv, io\nrows = list(csv.DictReader(io.StringIO(\'name,qty\\n"Tea, green",2\\n\')))\nprint(rows[0]["name"])  # Tea, green',
        ['Read `products.csv` with `DictReader` into `rows`.', 'Set `first_name` to the complete first product name.', 'Set `units` to the sum of numeric `qty` values.'],
        'import csv\n',
        'import csv\nwith open("products.csv", newline="", encoding="utf-8") as file:\n    rows = list(csv.DictReader(file))\nfirst_name = rows[0]["name"]\nunits = sum(int(row["qty"]) for row in rows)',
        [('Preserve the quoted comma', 'assert first_name == "Tea, green"'), ('Read both records correctly', 'assert len(rows) == 2 and units == 5')],
        ['Use the CSV parser, not string splitting.', 'The first name is still one field.', 'Convert qty before summing.'],
        'The file contains two columns per row despite the extra comma inside a quoted product name.',
        ['Quotes enclose the complete product field.', 'DictReader recognises the embedded comma.', 'The returned string contains the comma but not the enclosing CSV quotes.'], 'CSV quoting is a format rule, not ordinary Python string quoting.', files={'products.csv':'name,qty\n"Tea, green",2\nCoffee,3\n'})
    add('files', 'csv', 'write-csv', 'Write headers in a chosen order',
        'DictWriter uses fieldnames to choose the output columns and their order. Call writeheader once, then writerows for the records. Opening with newline="" lets the CSV module manage line endings, including on Windows. A CSV writer also quotes fields when needed, so a product name containing a comma remains one field when the file is read again.',
        'writer = csv.DictWriter(file, fieldnames=["name", "qty"])\nwriter.writeheader()\nwriter.writerows(records)',
        ['Write `records` to `stock.csv` with columns `name` then `qty`.', 'Include the header and both `records`.'],
        'import csv\nrecords = [{"qty": 2, "name": "Tea, green"}, {"qty": 3, "name": "Coffee"}]\n',
        'import csv\nrecords = [{"qty": 2, "name": "Tea, green"}, {"qty": 3, "name": "Coffee"}]\nwith open("stock.csv", "w", newline="", encoding="utf-8") as file:\n    writer = csv.DictWriter(file, fieldnames=["name", "qty"])\n    writer.writeheader()\n    writer.writerows(records)',
        [('Write ordered headers and valid quoted rows', 'import csv\nwith open("stock.csv", newline="", encoding="utf-8") as f:\n    reader = csv.DictReader(f)\n    assert reader.fieldnames == ["name", "qty"]\n    assert list(reader) == [{"name": "Tea, green", "qty": "2"}, {"name": "Coffee", "qty": "3"}]')],
        ['Open stock.csv for writing with newline="".', 'Create DictWriter with the required field order.', 'Write the header before the records.'],
        'Reading the output back checks the actual file format, rather than only checking that a file exists.',
        ['fieldnames defines the output schema.', 'writeheader writes those column names.', 'writerows serialises the data and handles quoting.'], 'Dictionary insertion order does not replace an explicit CSV column contract.')
    add('files', 'json', 'nested-json', 'Read records inside a JSON response',
        'A JSON file can contain metadata and records together. json.load returns Python dictionaries and lists reflecting that structure. Inspect the outer keys before treating the result as a table. Here data contains the records while page is metadata. Looping over the outer dictionary would visit key names rather than the records you want.',
        'payload = {"page": 1, "data": [{"value": 3}]}\nrecords = payload["data"]\nprint(records[0]["value"])  # 3',
        ['Read `response.json` into `payload`.', 'Set `names` to the `name` values inside `payload["data"]`, preserving order.', 'Set `total_units` to the sum of their `units`.'],
        'import json\n',
        'import json\nwith open("response.json", encoding="utf-8") as file:\n    payload = json.load(file)\nnames = [record["name"] for record in payload["data"]]\ntotal_units = sum(record["units"] for record in payload["data"])',
        [('Select the nested records', 'assert names == ["Tea", "Cake"]'), ('Sum JSON numbers', 'assert total_units == 7')],
        ['The outer object is a dictionary.', 'Select data before iterating.', 'JSON already represents units as numbers.'],
        'The same structure appears in API responses. Separate metadata from the records before performing analysis.',
        ['payload holds the complete response.', 'data holds a list of records.', 'Each record is another dictionary.'], 'json.load reads from a file; json.loads parses an already available string.', files={'response.json':'{"page": 1, "data": [{"name": "Tea", "units": 4}, {"name": "Cake", "units": 3}]}'})
    add('files', 'json', 'defaults', 'Handle optional fields explicitly',
        'A record schema may allow optional fields. get(key, default) handles an absent key, but it does not replace an existing None value. Choose the missing-value policy deliberately. In this sample, an absent discount means zero discount; quantity and price are always present. Preserving that distinction avoids masking errors in required fields.',
        'record = {"price": 10}\nprint(record.get("discount", 0))  # 0',
        ['Read `orders.json`.', 'Create `totals` with `price * qty - discount` for each record.', 'Treat an absent `discount` as 0; `discount` is an absolute amount, not a percentage.'],
        'import json\n',
        'import json\nwith open("orders.json", encoding="utf-8") as file:\n    orders = json.load(file)\ntotals = [row["price"] * row["qty"] - row.get("discount", 0) for row in orders]',
        [('Apply the optional discount rule', 'assert totals == [20, 21, 0]')],
        ['Use direct key access for required fields.', 'Use get("discount", 0) for the optional field.', 'Subtract the discount after multiplying price by qty.'],
        'Required and optional fields deserve different handling. A default should reflect a stated rule, not conceal missing data indiscriminately.',
        ['The discount key is absent.', 'get supplies its default in that case.', 'A present zero would be returned unchanged.'], 'get does not catch errors in unrelated required keys.', files={'orders.json':'[{"price": 10, "qty": 2}, {"price": 8, "qty": 3, "discount": 3}, {"price": 0, "qty": 1}]'})
    add('files', 'json', 'rejected', 'Keep track of rejected records',
        'Skipping bad rows silently makes an analysis hard to audit. Keep a count of rejected values alongside the valid data. Catch only the expected conversion error. Stripping whitespace before conversion makes the intended input policy clear. Here blank lines and non-integer values are rejected; zero and negative integer text remain valid observations.',
        'try:\n    value = int("bad")\nexcept ValueError:\n    rejected += 1',
        ['Read `amounts.txt` and parse each stripped line as an integer.', 'Store successful values in `valid` and the rejected line count in `rejected`.'],
        'valid = []\nrejected = 0\n',
        'valid = []\nrejected = 0\nwith open("amounts.txt", encoding="utf-8") as file:\n    for line in file:\n        try:\n            valid.append(int(line.strip()))\n        except ValueError:\n            rejected += 1',
        [('Keep valid signed integers and zero', 'assert valid == [10, 0, -2]'), ('Count all rejected lines', 'assert rejected == 3')],
        ['Attempt conversion inside the loop.', 'Append only after int() succeeds.', 'Increment rejected inside except ValueError.'],
        'The three accepted and three rejected lines account for the whole input. This reconciliation helps reveal accidental data loss.',
        ['Only conversion belongs in the protected operation.', 'Bad text raises ValueError.', 'The rejection count makes the skipped input visible.'], 'A broad except can hide programming errors along with invalid data.', files={'amounts.txt':'10\n\nnope\n0\n3.5\n-2\n'})
    add('files', 'json', 'merge-review', 'Checkpoint · combine monthly exports',
        'Combine several files with the same schema into one report. The header belongs once in the output, even though every source file has its own header. Read each source with a parser, collect its records in the required order, then write a fresh output. This is a common automation pattern for monthly or departmental exports.',
        'combined = []\n# For each file, extend combined with its parsed data rows.',
        ['Read `jan.csv` then `feb.csv` and combine their data rows into `combined`.', 'Calculate `revenue` as the numeric sum of `amount`.', 'Write `combined.csv` with `month,amount` headers and all three rows.'],
        'import csv\nfilenames = ["jan.csv", "feb.csv"]\n',
        'import csv\nfilenames = ["jan.csv", "feb.csv"]\ncombined = []\nfor filename in filenames:\n    with open(filename, newline="", encoding="utf-8") as file:\n        combined.extend(csv.DictReader(file))\nrevenue = sum(float(row["amount"]) for row in combined)\nwith open("combined.csv", "w", newline="", encoding="utf-8") as file:\n    writer = csv.DictWriter(file, fieldnames=["month", "amount"])\n    writer.writeheader()\n    writer.writerows(combined)',
        [('Combine data rows in file order', 'assert combined == [{"month": "Jan", "amount": "10"}, {"month": "Jan", "amount": "20"}, {"month": "Feb", "amount": "15"}]'), ('Calculate the numeric total', 'assert revenue == 45'), ('Export one valid table', 'import csv\nassert list(csv.DictReader(open("combined.csv", newline="", encoding="utf-8"))) == combined')],
        ['DictReader consumes each source header.', 'Use extend to add its individual rows.', 'Write a new header once, after all reading is done.'],
        'Combining parsed records avoids repeated header rows and preserves valid CSV quoting. The result is ready for a larger analysis.',
        ['An empty list collects records across files.', 'Each reader interprets its own header.', 'The output writer uses one shared schema.'], 'Concatenating raw CSV text often leaves repeated headers in the middle of the data.', kind='checkpoint', minutes=22, files={'jan.csv':'month,amount\nJan,10\nJan,20\n','feb.csv':'month,amount\nFeb,15\n'})

    add('analysis', 'statistics', 'proportions', 'Choose the denominator',
        'A percentage is a count divided by the relevant total, multiplied by 100. The denominator defines the meaning: orders delivered on time divided by all delivered orders is different from division by all orders placed. State the population in the variable names. Keep proportions as numbers during calculation and format only when presenting them.',
        'on_time = 18\ndelivered = 20\nrate = on_time / delivered * 100\nprint(rate)  # 90.0',
        ['Set `delivery_rate` to `delivered` as a percentage of `placed`.', 'Set `punctuality_rate` to `on_time` as a percentage of `delivered`.', 'Round both to one decimal place.'],
        'placed = 50\ndelivered = 40\non_time = 30\n',
        'placed = 50\ndelivered = 40\non_time = 30\ndelivery_rate = round(delivered / placed * 100, 1)\npunctuality_rate = round(on_time / delivered * 100, 1)',
        [('Measure delivery among placed orders', 'assert delivery_rate == 80'), ('Measure punctuality among deliveries', 'assert punctuality_rate == 75')],
        ['Each rate uses a different population.', 'Use placed for delivery_rate and delivered for punctuality_rate.', 'Multiply each ratio by 100.'],
        'The same numerator can support different percentages depending on the denominator. Label rates precisely when reporting them.',
        ['18 is the count of successful outcomes.', '20 defines the eligible population.', 'Multiplication by 100 converts a fraction into percent.'], 'A percentage without a clear denominator is easy to misinterpret.')
    add('analysis', 'statistics', 'weighted', 'Do not average averages blindly',
        'Group averages should not receive equal weight when the groups contain different numbers of observations. Reconstruct each group total as average times count, add those totals, and divide by the combined count. This produces the overall average. A simple average of group means would answer a different question: the average of a typical group, regardless of its size.',
        'means = [10, 20]\ncounts = [1, 3]\nweighted = (10 * 1 + 20 * 3) / 4\nprint(weighted)  # 17.5',
        ['Write `weighted_mean(means, counts)`. Lists are equal length and weights are nonnegative.', 'Return `None` if the total weight is zero; otherwise return the weighted mean without rounding.'],
        'def weighted_mean(means, counts):\n    pass\n',
        'def weighted_mean(means, counts):\n    weight = sum(counts)\n    if weight == 0:\n        return None\n    return sum(mean * count for mean, count in zip(means, counts)) / weight',
        [('Account for unequal group sizes', 'assert weighted_mean([10, 20], [1, 3]) == 17.5'), ('Handle a zero-weight group', 'assert weighted_mean([99, 4], [0, 2]) == 4'), ('Handle no observations', 'assert weighted_mean([], []) is None and weighted_mean([5], [0]) is None')],
        ['zip pairs each mean with its count.', 'Multiply each pair and sum those products.', 'Divide by the sum of counts, after checking for zero.'],
        'Weights reflect how many observations each mean represents. This prevents small groups from having disproportionate influence on an overall average.',
        ['Each group mean is multiplied by its size.', 'The products reconstruct group totals.', 'The combined total is divided by the combined size.'], 'zip stops at the shorter input; validate lengths when that guarantee is not part of your input contract.')
    add('analysis', 'missing', 'group-means', 'Keep a count for every group',
        'A grouped mean needs both a total and an observation count for each category. Dividing every group total by the overall record count would produce incorrect results. Build two dictionaries or keep both measurements in a nested dictionary. Retain the counts when presenting the results, because a mean based on one observation is less informative than one based on many.',
        'totals = {"A": 30, "B": 8}\ncounts = {"A": 3, "B": 1}\nmeans = {key: totals[key] / counts[key] for key in totals}',
        ['Calculate `average_by_team` from `rows`, using each team’s own observation count.', 'Set `counts` to each team’s record count.'],
        'rows = [{"team": "A", "minutes": 10}, {"team": "B", "minutes": 30}, {"team": "A", "minutes": 20}, {"team": "A", "minutes": 15}]\n',
        'rows = [{"team": "A", "minutes": 10}, {"team": "B", "minutes": 30}, {"team": "A", "minutes": 20}, {"team": "A", "minutes": 15}]\ntotals = {}\ncounts = {}\nfor row in rows:\n    team = row["team"]\n    totals[team] = totals.get(team, 0) + row["minutes"]\n    counts[team] = counts.get(team, 0) + 1\naverage_by_team = {team: totals[team] / counts[team] for team in totals}',
        [('Keep group-specific counts', 'assert counts == {"A": 3, "B": 1}'), ('Calculate group-specific means', 'assert average_by_team == {"A": 15, "B": 30}')],
        ['Update a total and a count for each team.', 'Increment the count by one per row.', 'Divide each total by its matching count.'],
        'Team B’s mean comes from only one observation. The count is essential context when comparing it with team A.',
        ['Each key identifies a separate group.', 'The total and count must use the same key.', 'The final dictionary expresses the per-group division.'], 'Using len(rows) as every denominator mixes group and overall populations.')
    add('analysis', 'statistics', 'outliers', 'Flag unusual values without deleting them',
        'A rule for flagging unusual values is not proof that the values are wrong. You may need to investigate instead of deleting them. Here use a deliberately simple rule: flag values greater than twice the median. Keep the original data so the effect of the rule remains visible. The rule is a practice heuristic, not a universal statistical definition of an outlier.',
        'from statistics import median\nvalues = [2, 3, 4, 20]\nthreshold = 2 * median(values)  # 7.0',
        ['Set `threshold` to twice the median of `values`.', 'Create `flagged` containing `values` strictly greater than `threshold`.', 'Leave `values` unchanged.'],
        'from statistics import median\nvalues = [10, 12, 13, 14, 80]\n',
        'from statistics import median\nvalues = [10, 12, 13, 14, 80]\nthreshold = 2 * median(values)\nflagged = [value for value in values if value > threshold]',
        [('Calculate the stated threshold', 'assert threshold == 26'), ('Flag only qualifying values', 'assert flagged == [80]'), ('Preserve the observations', 'assert values == [10, 12, 13, 14, 80]')],
        ['Find the median first.', 'Multiply it by two.', 'Filter using >, not >=.'],
        '80 is a candidate for investigation under this rule. It might be an error or an important real event; the calculation alone cannot decide.',
        ['The middle of four sorted values is the mean of the two middle values.', 'The threshold is determined by the stated rule.', 'A flag calls for review rather than automatic deletion.'], 'Removing every unusual observation can erase the event your analysis is supposed to explain.')
    add('analysis', 'statistics', 'spread', 'Compare variability',
        'Two groups can have the same mean but very different variation. Standard deviation measures spread around the mean. statistics.pstdev describes the supplied values as a complete population. statistics.stdev estimates spread from a sample and requires at least two observations. In this exercise, treat each supplied list as the complete set you want to describe.',
        'from statistics import mean, pstdev\nprint(mean([4, 4, 4]))    # 4\nprint(pstdev([4, 4, 4]))  # 0.0',
        ['Set `mean_a` and `mean_b` to the two means.', 'Set `spread_a` and `spread_b` to population standard deviations.', 'Set `more_variable` to `"B"` if B has the greater spread, otherwise `"A"`.'],
        'from statistics import mean, pstdev\na = [10, 10, 10]\nb = [0, 10, 20]\n',
        'from statistics import mean, pstdev\na = [10, 10, 10]\nb = [0, 10, 20]\nmean_a = mean(a)\nmean_b = mean(b)\nspread_a = pstdev(a)\nspread_b = pstdev(b)\nmore_variable = "B" if spread_b > spread_a else "A"',
        [('Recognise equal means', 'assert mean_a == mean_b == 10'), ('Measure differing spread', 'assert spread_a == 0 and abs(spread_b - 8.16496580927726) < 1e-8'), ('Identify the more variable group', 'assert more_variable == "B"')],
        ['Use mean() for both centres.', 'Use pstdev(), not stdev(), for this stated population calculation.', 'Compare the standard deviations.'],
        'A constant series and a volatile series can share a mean. Spread provides information that the mean alone leaves out.',
        ['All observations in the example are identical.', 'Their deviations from the mean are zero.', 'The population standard deviation is therefore zero.'], 'Choose the population or sample formula based on your question, not whichever function name you remember first.')
    add('analysis', 'growth', 'rolling', 'Smooth a series with a moving average',
        'A moving average summarises a fixed-width window as it moves along a sequence. Here use trailing windows of three observations and return results only when a complete window exists. The first output therefore uses input positions zero through two. Keep the original order: sorting would destroy the time relationship you are trying to summarise.',
        'values = [3, 6, 9, 12]\nprint(sum(values[0:3]) / 3)  # 6.0\nprint(sum(values[1:4]) / 3)  # 9.0',
        ['Write `moving_average(values)`, returning the means of all complete trailing windows of size 3.', 'Return an empty list for fewer than 3 observations. Do not round.'],
        'def moving_average(values):\n    pass\n',
        'def moving_average(values):\n    return [sum(values[end-3:end]) / 3 for end in range(3, len(values) + 1)]',
        [('Move the window through the series', 'assert moving_average([3, 6, 9, 12, 15]) == [6, 9, 12]'), ('Handle short and exact-sized inputs', 'assert moving_average([1, 2]) == [] and moving_average([0, 0, 3]) == [1]'), ('Preserve order in a changing series', 'assert moving_average([9, 0, 0, 3]) == [3, 1]')],
        ['The first exclusive end index is 3.', 'Slice values[end-3:end] for each complete window.', 'Include len(values) as an end index.'],
        'The shorter output is intentional: the first two inputs do not yet have complete trailing windows.',
        ['Each slice contains three neighbouring observations.', 'The slice moves forward one position.', 'Its mean is associated with that window’s final observation.'], 'A moving average can hide sharp changes, so retain the raw series when interpreting trends.')
    add('analysis', 'growth', 'rank-ties', 'Make rankings predictable',
        'When scores tie, a ranking needs a secondary rule. sorted accepts a tuple as a key and compares its elements in order. A negative numeric score sorts high values first while the following name sorts ties alphabetically. Stating the tie rule makes the result stable and prevents arbitrary-looking changes between reports.',
        'rows = [{"name": "Bo", "score": 8}, {"name": "Ari", "score": 8}]\nranked = sorted(rows, key=lambda row: (-row["score"], row["name"]))',
        ['Write `rank_names(rows)`, returning names ordered by `score` descending.', 'Break equal-score ties by `name` ascending. Return an empty list for empty input.'],
        'def rank_names(rows):\n    pass\n',
        'def rank_names(rows):\n    ordered = sorted(rows, key=lambda row: (-row["score"], row["name"]))\n    return [row["name"] for row in ordered]',
        [('Apply the primary and tie rules', 'assert rank_names([{"name": "Zed", "score": 9}, {"name": "Bo", "score": 10}, {"name": "Ari", "score": 10}]) == ["Ari", "Bo", "Zed"]'), ('Handle empty and negative scores', 'assert rank_names([]) == [] and rank_names([{"name": "A", "score": -2}, {"name": "B", "score": -1}]) == ["B", "A"]')],
        ['Use a tuple key with two elements.', 'Negate the score for descending numeric order.', 'Keep name unmodified for ascending alphabetical order.'],
        'A single reverse=True would reverse both parts of a tuple key. Negating just the numeric part gives the mixed directions you need.',
        ['The first key element determines the main order.', 'Names are compared only when scores tie.', 'The output order follows an explicit policy.'], 'Alphabetical order here is Python’s ordinary string order; real human-language sorting may require locale-specific rules.')
    add('analysis', 'growth', 'audit-review', 'Checkpoint · an honest activity summary',
        'A report should reveal its data quality as well as its headline average. Write a reusable summary that treats None as missing, preserves valid zeros, and reports the number of usable observations. Use a clear empty-data policy. This checkpoint combines filtering, descriptive statistics, and structured function results in a fresh dataset.',
        'summary = {"valid_count": 3, "missing_count": 1, "mean": 8.0}',
        ['Write `summarise(values)`, returning `valid_count`, `missing_count`, `mean`, and `maximum`.', 'Ignore only `None`. Round `mean` to two decimals.', 'Use `None` for `mean` and `maximum` if there are no valid observations.'],
        'def summarise(values):\n    pass\n',
        'def summarise(values):\n    valid = [value for value in values if value is not None]\n    return {"valid_count": len(valid), "missing_count": len(values) - len(valid), "mean": round(sum(valid) / len(valid), 2) if valid else None, "maximum": max(valid) if valid else None}',
        [('Report measurements and quality together', 'assert summarise([0, 10, None, 20]) == {"valid_count": 3, "missing_count": 1, "mean": 10, "maximum": 20}'), ('Handle all-missing data', 'assert summarise([None]) == {"valid_count": 0, "missing_count": 1, "mean": None, "maximum": None}'), ('Handle empty and rounded results', 'assert summarise([])["maximum"] is None and summarise([1, 2, 2])["mean"] == 1.67')],
        ['Filter only None values.', 'Count excluded observations by subtracting the valid count from the input length.', 'Guard mean and maximum when valid is empty.'],
        'The summary makes excluded data visible. A mean without its observation count and missing-data policy is incomplete context.',
        ['Named fields describe each result.', 'Counts document the population behind the mean.', 'The structure can be saved as JSON or rendered in a report.'], 'Do not replace missing observations with zero unless that is an explicit, justified policy.', kind='checkpoint', minutes=22)

    from course_practice_applied import add_applied
    add_applied(add)
