"""The rest of the learning path. Data and automation exercises use disposable sample files."""


def extend(module, task):
    m = module('flow', 'Decisions & loops', 'Teach your scripts to choose, repeat, and filter.', 'Build a spending alert')
    task(m, 'conditions', 'Make a decision',
        'An if block runs only when its condition is true. elif checks another case; else handles what remains. Indent each block with four spaces. Comparisons such as >, >=, and == produce True or False. = assigns; == compares.',
        'temperature = 28\nif temperature >= 30:\n    label = "hot"\nelse:\n    label = "comfortable"',
        ['Set status to "over" if spent is greater than budget.', 'Otherwise set status to "within". Keep the provided inputs.'],
        'spent = 125\nbudget = 100\n\n# Choose a status.\n',
        'spent = 125\nbudget = 100\nif spent > budget:\n    status = "over"\nelse:\n    status = "within"',
        [('Detect an overspend', 'assert status == "over"')],
        ['Compare spent with budget.', 'Use if spent > budget: followed by an indented assignment.', 'Assign status = "over" in the first block and "within" in else.'],
        'Only one branch executes. Equality belongs to the within-budget case because the test uses > rather than >=.')
    task(m, 'for', 'Repeat without repetition',
        'A list stores an ordered sequence in square brackets. A for loop visits each item. Start an accumulator at zero, then add each value to it. += means add to the existing value.',
        'scores = [3, 5, 2]\ntotal = 0\nfor score in scores:\n    total += score',
        ['Use a for loop to add all expenses into total.', 'The expenses are 8, 12, 5, and 15. Print total.'],
        'expenses = [8, 12, 5, 15]\ntotal = 0\n\n# Add each expense.\n',
        'expenses = [8, 12, 5, 15]\ntotal = 0\nfor expense in expenses:\n    total += expense\nprint(total)',
        [('Add the expenses', 'assert total == 40'), ('Print the result', 'assert __output__.strip() == "40"'), ('Practice a for loop', 'import ast\nassert any(isinstance(n, ast.For) for n in ast.walk(ast.parse(open("main.py").read())))')],
        ['The accumulator starts outside the loop.', 'Inside for expense in expenses:, add expense to total.', 'Print after the loop, at the outer indentation level.'],
        'Initialize once, update on each iteration, and display after the loop. Initializing inside the loop would repeatedly reset your total.')
    task(m, 'filter', 'Keep the values that matter',
        'Combine a loop with an if to select values. An empty list is []. append(value) adds an item to the end. The conditional block is nested inside the loop, so it needs another level of indentation.',
        'scores = [4, 9, 6]\nhigh = []\nfor score in scores:\n    if score >= 6:\n        high.append(score)',
        ['Build a list called large containing expenses of 20 or more.', 'Preserve the original order.'],
        'expenses = [7, 20, 35, 12, 20]\nlarge = []\n',
        'expenses = [7, 20, 35, 12, 20]\nlarge = []\nfor expense in expenses:\n    if expense >= 20:\n        large.append(expense)',
        [('Include the boundary and preserve duplicates', 'assert large == [20, 35, 20]')],
        ['Check every expense, including values exactly equal to 20.', 'Use >= 20 for the condition.', 'Inside the if block, call large.append(expense).'],
        'A list preserves both order and duplicates. That matters when identical amounts represent separate transactions.')
    task(m, 'alert-1', 'Spending alert · spot the spikes',
        'Project 1 / 2. A week of spending should tell you where to look. Combine accumulation and filtering to create a compact summary.',
        'count = len([10, 20, 30])  # 3 items',
        ['Calculate total for the week.', 'Build high_days containing amounts greater than 30.', 'Set high_count to the number of high-spending days.'],
        'daily = [12, 45, 18, 32, 9, 60, 24]\n\n# Summarise the week.\n',
        'daily = [12, 45, 18, 32, 9, 60, 24]\ntotal = 0\nhigh_days = []\nfor amount in daily:\n    total += amount\n    if amount > 30:\n        high_days.append(amount)\nhigh_count = len(high_days)',
        [('Calculate the weekly total', 'assert total == 200'), ('Find the high-spending days', 'assert high_days == [45, 32, 60]'), ('Count three spikes', 'assert high_count == 3')],
        ['Maintain a total and a list as you visit the amounts.', 'Use append only when amount > 30.', 'len(high_days) gives the number of spikes.'],
        'One pass can calculate several useful measurements. Your filter uses > 30, so 30 itself would not be a spike.', kind='project', minutes=15)
    task(m, 'alert-2', 'Spending alert · take action',
        'Project 2 / 2. Turn the summary into a decision. Budget rules should be explicit at their boundaries so the message never surprises you.',
        'if used > limit:\n    message = "Reduce spending"',
        ['If total is greater than budget, set status to "over budget".', 'If they are equal, use "at budget". Otherwise use "under budget".', 'Create report as "200 spent | at budget | 3 high days" from the variables.'],
        'total = 200\nbudget = 200\nhigh_count = 3\n',
        'total = 200\nbudget = 200\nhigh_count = 3\nif total > budget:\n    status = "over budget"\nelif total == budget:\n    status = "at budget"\nelse:\n    status = "under budget"\nreport = f"{total} spent | {status} | {high_count} high days"\nprint(report)',
        [('Handle equality', 'assert status == "at budget"'), ('Build the report', 'assert report == "200 spent | at budget | 3 high days"')],
        ['There are three mutually exclusive cases.', 'Check greater-than first, then equality with elif.', 'Use an f-string to combine total, status, and high_count.'],
        'You have turned raw daily amounts into a decision and a readable report. Boundary cases like exact equality deserve deliberate handling.', kind='project', minutes=15)

    m = module('collections', 'Lists & dictionaries', 'Organise records and answer questions about them.', 'Analyse a tiny shop')
    task(m, 'lists', 'Work with a sequence',
        'List positions start at zero. items[0] is the first item and items[-1] is the last. A slice such as items[:2] returns the first two. sorted(items) returns a new sorted list and leaves the original alone.',
        'cities = ["Lima", "Oslo", "Accra"]\nfirst = cities[0]\nordered = sorted(cities)',
        ['Set first to the first reading and last to the last reading.', 'Set ordered to the readings sorted from low to high.', 'Keep readings unchanged.'],
        'readings = [18, 12, 25, 16]\n',
        'readings = [18, 12, 25, 16]\nfirst = readings[0]\nlast = readings[-1]\nordered = sorted(readings)',
        [('Read both ends', 'assert first == 18 and last == 16'), ('Sort without changing the source', 'assert ordered == [12, 16, 18, 25] and readings == [18, 12, 25, 16]')],
        ['The first index is 0, not 1.', 'Use -1 for the last position.', 'Use sorted(readings), rather than readings.sort(), to preserve the original.'],
        'Choosing between a new list and an in-place change matters when you need to preserve source data.')
    task(m, 'dicts', 'Give a record some structure',
        'A dictionary connects unique keys to values. record["name"] reads a key. record.get("discount", 0) supplies a fallback when a key is absent. Assigning to a key creates or updates its value.',
        'product = {"name": "Tea", "price": 6}\nprice = product["price"]\nproduct["stock"] = 12',
        ['Calculate subtotal from the order price and quantity.', 'Read discount with a default of 0.', 'Store the final amount in order["total"].'],
        'order = {"item": "Notebook", "price": 12, "quantity": 3}\n',
        'order = {"item": "Notebook", "price": 12, "quantity": 3}\nsubtotal = order["price"] * order["quantity"]\ndiscount = order.get("discount", 0)\norder["total"] = subtotal - discount',
        [('Calculate subtotal', 'assert subtotal == 36'), ('Use a missing-key fallback', 'assert discount == 0'), ('Update the order record', 'assert order["total"] == 36')],
        ['Read the price and quantity using their keys.', 'get() avoids a KeyError when discount is missing.', 'Assign the calculated final amount to the total key.'],
        'Dictionaries make records readable: a name such as quantity is easier to understand than a positional index.')
    task(m, 'comprehensions', 'Transform a collection',
        'A list comprehension builds a new list from an existing sequence. The expression comes first, followed by for. An optional if filters which items are included. Read it as: make this value for each matching item.',
        'values = [2, 4, 6]\ndoubled = [value * 2 for value in values if value > 2]',
        ['Create cleaned by stripping whitespace and lowercasing each nonblank name.', 'Exclude names that become empty after stripping.', 'Preserve order and duplicates.'],
        'names = [" Alice ", "", " BOB", "   ", "Alice"]\n',
        'names = [" Alice ", "", " BOB", "   ", "Alice"]\ncleaned = [name.strip().lower() for name in names if name.strip()]',
        [('Clean and filter names', 'assert cleaned == ["alice", "bob", "alice"]')],
        ['strip() removes whitespace at both ends; lower() normalises letter case.', 'Filter using if name.strip(), because an empty string is false.', 'Put name.strip().lower() before the for part.'],
        'Normalise text before grouping or comparing it. Otherwise Alice and ALICE could be treated as different people.')
    orders = 'orders = [\n    {"item": "Tea", "qty": 2, "price": 5},\n    {"item": "Coffee", "qty": 1, "price": 8},\n    {"item": "Tea", "qty": 3, "price": 5},\n]\n'
    task(m, 'shop-1', 'Tiny shop · find the revenue',
        'Project 1 / 2. Each shop order is a dictionary, and the day is a list of orders. Calculate revenue from quantity times unit price, not from either field alone.',
        'line_total = record["qty"] * record["price"]',
        ['Build line_totals with the revenue of each order.', 'Calculate revenue for the whole day.', 'Calculate units sold across all orders.'],
        orders,
        orders+'line_totals = [order["qty"] * order["price"] for order in orders]\nrevenue = sum(line_totals)\nunits = sum(order["qty"] for order in orders)',
        [('Calculate every line', 'assert line_totals == [10, 8, 15]'), ('Total revenue is 33', 'assert revenue == 33'), ('Six units were sold', 'assert units == 6')],
        ['Work with one order at a time.', 'sum() adds a sequence of numbers.', 'Revenue uses qty * price; units uses qty alone.'],
        'Revenue and units answer different business questions. Naming them clearly prevents misleading summaries.', kind='project', minutes=15)
    task(m, 'shop-2', 'Tiny shop · group the sales',
        'Project 2 / 2. Group repeated products into one total per item. Start with an empty dictionary and add each order to its product’s running revenue.',
        'totals = {}\ntotals["Tea"] = totals.get("Tea", 0) + 10',
        ['Create by_item mapping each product name to its total revenue.', 'Tea should contribute 25 and Coffee 8.', 'Set top_item to the name with the highest revenue.'],
        orders+'\nby_item = {}\n',
        orders+'by_item = {}\nfor order in orders:\n    name = order["item"]\n    by_item[name] = by_item.get(name, 0) + order["qty"] * order["price"]\ntop_item = max(by_item, key=by_item.get)',
        [('Group repeated products', 'assert by_item == {"Tea": 25, "Coffee": 8}'), ('Identify the leading product', 'assert top_item == "Tea"')],
        ['Use the product name as the dictionary key.', 'get(name, 0) provides the initial total for a new product.', 'max(by_item, key=by_item.get) compares the values and returns the winning key.'],
        'Grouping is a core analysis operation. You will use the same idea with CSV rows and pandas tables later.', kind='project', minutes=18)

    m = module('functions', 'Reusable functions', 'Write code that works for more than one input.', 'Build a receipt calculator')
    task(m, 'return', 'Turn a calculation into a tool',
        'def creates a function. Parameters are names for inputs. return sends a result back to the caller; print only displays it. A function can be tested with many inputs without rewriting its body.',
        'def double(value):\n    return value * 2\n\nanswer = double(6)',
        ['Write line_total(price, quantity) returning price multiplied by quantity.', 'It should handle zero quantities and decimal prices.'],
        'def line_total(price, quantity):\n    # Return the calculated amount.\n    pass\n',
        'def line_total(price, quantity):\n    return price * quantity',
        [('Calculate an ordinary order', 'assert line_total(12, 3) == 36'), ('Handle a decimal price', 'assert line_total(2.5, 3) == 7.5'), ('Handle zero quantity', 'assert line_total(10, 0) == 0')],
        ['Use the parameters, rather than fixed numbers.', 'The caller needs a returned number, not console output.', 'Replace pass with return price * quantity.'],
        'These checks call your function with different inputs. A reusable function generalises beyond the example on screen.')
    task(m, 'defaults', 'Make the common case easy',
        'A default parameter is used when the caller leaves that argument out. Keep required parameters first. For percentage calculations, 10% is 0.10. round(value, 2) rounds the result to two decimal places.',
        'def add_fee(amount, fee=2):\n    return amount + fee',
        ['Write discounted(amount, percent=10).', 'Return the amount after applying the percentage discount, rounded to two decimals.', 'A 0 percent discount should leave the amount unchanged.'],
        'def discounted(amount, percent=10):\n    pass\n',
        'def discounted(amount, percent=10):\n    return round(amount * (1 - percent / 100), 2)',
        [('Apply the default 10 percent', 'assert discounted(80) == 72'), ('Support an explicit percentage', 'assert discounted(49.99, 15) == 42.49'), ('Support no discount', 'assert discounted(19, 0) == 19')],
        ['Convert percent into a fraction by dividing by 100.', 'Multiply amount by the fraction that remains.', 'Return round(amount * (1 - percent / 100), 2).'],
        'A default keeps frequent calls short while preserving control for less common cases.')
    task(m, 'validation', 'Handle a bad input',
        'Conversion can fail. try runs code that might raise an exception; except ValueError handles a failed conversion. Catch the specific failure you expect, so unrelated bugs still remain visible.',
        'try:\n    number = int("hello")\nexcept ValueError:\n    number = 0',
        ['Write parse_quantity(text) that returns an integer for valid nonnegative integer text.', 'Return None for invalid text or negative quantities.', 'Inputs will always be strings.'],
        'def parse_quantity(text):\n    pass\n',
        'def parse_quantity(text):\n    try:\n        quantity = int(text)\n    except ValueError:\n        return None\n    if quantity < 0:\n        return None\n    return quantity',
        [('Parse valid and zero quantities', 'assert parse_quantity("4") == 4 and parse_quantity("0") == 0'), ('Handle text and decimal input', 'assert parse_quantity("many") is None and parse_quantity("2.5") is None'), ('Reject a negative quantity', 'assert parse_quantity("-1") is None')],
        ['Call int(text) inside a try block.', 'When conversion raises ValueError, return None.', 'After conversion, check for a negative number before returning quantity.'],
        'Invalid input is different from a valid zero. Returning None lets a caller distinguish the two.')
    task(m, 'receipt-1', 'Receipt calculator · subtotal',
        'Project 1 / 2. Build a function that accepts a list of order dictionaries. An empty basket should produce zero. The function must leave its input unchanged.',
        'def count_items(items):\n    return len(items)',
        ['Write subtotal(items), adding price * qty for every record.', 'Return 0 for an empty list.', 'Do not modify the input records.'],
        'def subtotal(items):\n    pass\n\n# Try your function with a sample basket.\n',
        'def subtotal(items):\n    return sum(item["price"] * item["qty"] for item in items)',
        [('Handle multiple products', 'assert subtotal([{"price": 5, "qty": 2}, {"price": 8, "qty": 3}]) == 34'), ('Handle an empty basket', 'assert subtotal([]) == 0'), ('Preserve the input', 'basket = [{"price": 2.5, "qty": 4}]\nassert subtotal(basket) == 10 and basket == [{"price": 2.5, "qty": 4}]')],
        ['Start an accumulator at zero, or use sum().', 'Use keys price and qty for each item.', 'sum(item["price"] * item["qty"] for item in items) handles empty input too.'],
        'A function that leaves its inputs unchanged is easier to reuse, because callers can rely on their data remaining intact.', kind='project', minutes=15)
    task(m, 'receipt-2', 'Receipt calculator · final bill',
        'Project 2 / 2. Add a percentage discount, then calculate tax on the discounted amount. Documenting this order matters: different rules produce different totals.',
        'after_discount = amount * (1 - discount / 100)\ntax_amount = after_discount * tax / 100',
        ['Write checkout(amount, discount=0, tax=6).', 'Return a dictionary with subtotal, discount_amount, tax_amount, and total.', 'Calculate from unrounded intermediate values; round each returned value to two decimals.'],
        'def checkout(amount, discount=0, tax=6):\n    pass\n',
        'def checkout(amount, discount=0, tax=6):\n    saving = amount * discount / 100\n    taxable = amount - saving\n    tax_due = taxable * tax / 100\n    return {"subtotal": round(amount, 2), "discount_amount": round(saving, 2), "tax_amount": round(tax_due, 2), "total": round(taxable + tax_due, 2)}',
        [('Use default tax with no discount', 'assert checkout(100) == {"subtotal": 100, "discount_amount": 0, "tax_amount": 6, "total": 106}'), ('Apply discount before tax', 'assert checkout(100, 10, 6) == {"subtotal": 100, "discount_amount": 10, "tax_amount": 5.4, "total": 95.4}'), ('Handle zero and rounding', 'assert checkout(0)["total"] == 0 and checkout(19.99, 5, 6)["total"] == 20.13')],
        ['Calculate the saving first, then subtract it from amount.', 'Apply tax to the reduced amount.', 'Return all four named values in a dictionary, rounding only at the end.'],
        'You have composed several business rules into one testable function. For production monetary calculations, use Decimal and the rounding rules required by the application.', kind='project', minutes=20)

    m = module('files', 'Files, CSV & JSON', 'Read messy inputs and write useful outputs.', 'Clean a contact list')
    task(m, 'text', 'Read a file, safely',
        'with open(...) closes a file automatically when the block ends. Reading text returns a string. splitlines() divides it into lines without keeping newline characters. Sample files are recreated for each run, in a temporary practice folder.',
        'with open("notes.txt", encoding="utf-8") as file:\n    text = file.read()\nlines = text.splitlines()',
        ['Read tasks.txt.', 'Create tasks containing nonblank lines with surrounding whitespace removed.', 'Set count to the number of tasks.'],
        '# Read the sample file and clean its lines.\n',
        'with open("tasks.txt", encoding="utf-8") as file:\n    text = file.read()\ntasks = [line.strip() for line in text.splitlines() if line.strip()]\ncount = len(tasks)',
        [('Clean the file contents', 'assert tasks == ["Check sales", "Email team", "Back up report"]'), ('Count the tasks', 'assert count == 3')],
        ['Open tasks.txt in read mode with UTF-8 encoding.', 'Split the text into lines, then strip each line.', 'Filter out lines whose stripped value is empty.'],
        'Explicit encoding avoids platform-dependent text decoding. A context manager closes the file even if later code fails.', files={'tasks.txt':' Check sales \n\nEmail team\n  \nBack up report\n'})
    sales = {'sales.csv':'product,quantity,price\nTea,2,5.00\nCoffee,3,8.00\nTea,1,5.00\n'}
    task(m, 'csv', 'Read rows with column names',
        'The csv module understands CSV quoting and separators. csv.DictReader returns each row as a dictionary using the header names. Its values are strings, so convert numeric fields before calculating. Use newline="" when opening CSV files.',
        'import csv\nwith open("data.csv", newline="", encoding="utf-8") as file:\n    rows = list(csv.DictReader(file))',
        ['Read sales.csv into rows using DictReader.', 'Calculate revenue from quantity * price for every row.', 'Set row_count to the number of data rows.'],
        'import csv\n\n# Read and summarise sales.csv.\n',
        'import csv\nwith open("sales.csv", newline="", encoding="utf-8") as file:\n    rows = list(csv.DictReader(file))\nrevenue = sum(int(row["quantity"]) * float(row["price"]) for row in rows)\nrow_count = len(rows)',
        [('Read all data rows', 'assert row_count == 3 and len(rows) == 3'), ('Calculate numeric revenue', 'assert revenue == 39')],
        ['Use list(csv.DictReader(file)) while the file is open.', 'Convert quantity with int() and price with float().', 'Sum the product of the two fields over rows.'],
        'CSV readers handle quoted fields that a simple split(",") would misread. Numeric conversion is a separate step.', files=sales)
    task(m, 'json', 'Save structured results',
        'JSON stores structured values such as dictionaries, lists, strings, and numbers. json.load(file) reads JSON; json.dump(data, file) writes it. Unlike CSV, JSON preserves numeric types. indent=2 makes saved output easier to read.',
        'import json\nwith open("result.json", "w", encoding="utf-8") as file:\n    json.dump({"count": 3}, file, indent=2)',
        ['Read settings.json into settings.', 'Increase settings["target"] by 5.', 'Write the updated dictionary to updated.json, keeping the name unchanged.'],
        'import json\n',
        'import json\nwith open("settings.json", encoding="utf-8") as file:\n    settings = json.load(file)\nsettings["target"] += 5\nwith open("updated.json", "w", encoding="utf-8") as file:\n    json.dump(settings, file, indent=2)',
        [('Update the in-memory data', 'assert settings == {"name": "Weekly review", "target": 15}'), ('Write valid JSON with the result', 'import json\nassert json.load(open("updated.json", encoding="utf-8")) == {"name": "Weekly review", "target": 15}')],
        ['Use json.load() with the open input file.', 'Update the target key before writing.', 'Open updated.json with mode "w" and call json.dump(settings, file, indent=2).'],
        'Writing an output file separately preserves the original input. Practice outputs disappear after a run; later automation lessons teach repeatable file workflows.', files={'settings.json':'{"name": "Weekly review", "target": 10}'})
    contacts = {'contacts.csv':'name,email\n Alice ,ALICE@example.com \nBob,bob@example.com\nAlice duplicate,alice@example.com\nNo email,\n Cara , CARA@example.com\n'}
    task(m, 'contacts-1', 'Contact cleaner · normalise',
        'Project 1 / 2. A contact export contains inconsistent whitespace, letter case, and missing addresses. First make the records comparable. Treat a nonempty email as present; full email validation is outside this exercise.',
        'clean = raw.strip().lower()',
        ['Read contacts.csv.', 'Build cleaned as dictionaries with stripped name and stripped, lowercase email.', 'Exclude rows whose email becomes blank. Keep duplicates for this step.'],
        'import csv\n\n# Build a cleaned list of contact dictionaries.\n',
        'import csv\nwith open("contacts.csv", newline="", encoding="utf-8") as file:\n    rows = list(csv.DictReader(file))\ncleaned = []\nfor row in rows:\n    email = row["email"].strip().lower()\n    if email:\n        cleaned.append({"name": row["name"].strip(), "email": email})',
        [('Exclude the empty email', 'assert len(cleaned) == 4'), ('Normalise names and addresses', 'assert cleaned == [{"name": "Alice", "email": "alice@example.com"}, {"name": "Bob", "email": "bob@example.com"}, {"name": "Alice duplicate", "email": "alice@example.com"}, {"name": "Cara", "email": "cara@example.com"}]')],
        ['Load dictionaries with csv.DictReader.', 'Normalise email before checking whether it is blank.', 'Append a new dictionary containing the two cleaned fields.'],
        'Cleaning before deduplication prevents case and whitespace differences from hiding duplicate addresses.', kind='project', minutes=18, files=contacts)
    task(m, 'contacts-2', 'Contact cleaner · deduplicate & export',
        'Project 2 / 2. Keep the first contact for each email and write the result to CSV. A set tracks unique values efficiently. DictWriter writes dictionaries in the field order you specify; writeheader() writes the column names.',
        'seen = set()\nseen.add("first@example.com")\n# writer = csv.DictWriter(file, fieldnames=["name", "email"])',
        ['Deduplicate cleaned by email, preserving the first occurrence and input order, into unique.', 'Write unique to clean_contacts.csv with name,email headers.', 'Use newline="" when opening the output file.'],
        'import csv\ncleaned = [\n    {"name": "Alice", "email": "alice@example.com"},\n    {"name": "Bob", "email": "bob@example.com"},\n    {"name": "Alice duplicate", "email": "alice@example.com"},\n]\n',
        'import csv\ncleaned = [{"name": "Alice", "email": "alice@example.com"}, {"name": "Bob", "email": "bob@example.com"}, {"name": "Alice duplicate", "email": "alice@example.com"}]\nseen = set()\nunique = []\nfor row in cleaned:\n    if row["email"] not in seen:\n        unique.append(row)\n        seen.add(row["email"])\nwith open("clean_contacts.csv", "w", newline="", encoding="utf-8") as file:\n    writer = csv.DictWriter(file, fieldnames=["name", "email"])\n    writer.writeheader()\n    writer.writerows(unique)',
        [('Keep the first record for each email', 'assert unique == [{"name": "Alice", "email": "alice@example.com"}, {"name": "Bob", "email": "bob@example.com"}]'), ('Export the cleaned records', 'import csv\nassert list(csv.DictReader(open("clean_contacts.csv", newline="", encoding="utf-8"))) == unique')],
        ['Use a set for seen email addresses and a list for the retained records.', 'Only append a row when its email is not in seen.', 'Create DictWriter, call writeheader(), then writerows(unique).'],
        'The list preserves display order while the set handles membership checks. You now have a complete read–clean–export workflow.', kind='project', minutes=20)

    m = module('analysis', 'Practical data analysis', 'Summarise, group, and question the numbers.', 'Create a sales report')
    task(m, 'statistics', 'Look beyond the average',
        'The mean is total divided by count. The median is the middle of sorted observations. A few unusually large values can pull the mean away from a typical observation. The statistics module calculates both.',
        'from statistics import mean, median\nvalues = [10, 12, 14]\nprint(mean(values), median(values))',
        ['Calculate average and middle for the provided delivery times.', 'Set spread to maximum minus minimum.', 'Keep results numeric; no rounding is necessary.'],
        'from statistics import mean, median\nminutes = [12, 14, 15, 16, 63]\n',
        'from statistics import mean, median\nminutes = [12, 14, 15, 16, 63]\naverage = mean(minutes)\nmiddle = median(minutes)\nspread = max(minutes) - min(minutes)',
        [('Calculate the mean', 'assert average == 24'), ('Calculate the median', 'assert middle == 15'), ('Calculate the range', 'assert spread == 51')],
        ['Use mean(minutes) and median(minutes).', 'The range uses the largest and smallest observations.', 'Subtract min(minutes) from max(minutes).'],
        'The mean is 24 but the median is 15. One 63-minute delivery changes the mean substantially; do not describe a distribution using only one number.')
    task(m, 'missing', 'Treat missing data deliberately',
        'Missing values and zero mean different things. None often marks an unavailable value. Filter with is not None to keep valid zeros. A function should define what it returns when there are no usable values.',
        'values = [0, None, 10]\nvalid = [value for value in values if value is not None]',
        ['Write safe_mean(values), ignoring None but retaining zero.', 'Return None when there are no valid values.', 'Otherwise return the arithmetic mean.'],
        'def safe_mean(values):\n    pass\n',
        'def safe_mean(values):\n    valid = [value for value in values if value is not None]\n    if not valid:\n        return None\n    return sum(valid) / len(valid)',
        [('Ignore missing observations', 'assert safe_mean([10, None, 20]) == 15'), ('Retain valid zero observations', 'assert safe_mean([0, None, 10]) == 5'), ('Handle empty and all-missing input', 'assert safe_mean([]) is None and safe_mean([None, None]) is None')],
        ['Do not filter with if value: that would remove zero.', 'Use if value is not None.', 'Check whether the valid list is empty before dividing by its length.'],
        'Dropping zeros would inflate the mean. Missing-data decisions directly affect the conclusions of an analysis.')
    task(m, 'growth', 'Compare two periods',
        'Percentage change compares the difference with the original value: (current - previous) / previous * 100. A negative result means a decrease. When the original value is zero, the usual percentage change is undefined.',
        'change = (120 - 100) / 100 * 100  # 20 percent',
        ['Write growth(previous, current). Return percent change rounded to one decimal place.', 'Return None when previous is zero.', 'Handle decreases as negative percentages.'],
        'def growth(previous, current):\n    pass\n',
        'def growth(previous, current):\n    if previous == 0:\n        return None\n    return round((current - previous) / previous * 100, 1)',
        [('Measure an increase', 'assert growth(80, 100) == 25'), ('Measure a decrease', 'assert growth(100, 75) == -25'), ('Round and handle the zero baseline', 'assert growth(30, 40) == 33.3 and growth(0, 12) is None')],
        ['Use the previous value as the denominator.', 'Handle a zero previous value before doing division.', 'Multiply the relative change by 100 and round to one decimal place.'],
        'Growth from zero cannot be expressed with this formula. Returning None communicates that absence instead of inventing a percentage.')
    report_files = {'orders.csv':'region,revenue\nNorth,120\nSouth,80\nNorth,100\nWest,50\nSouth,120\nWest,30\n'}
    task(m, 'report-1', 'Sales report · regional totals',
        'Project 1 / 2. Your brief: understand where revenue comes from. Read the data, group by region, then identify the region with the greatest total. All revenue values in this sample are present and numeric.',
        'totals[key] = totals.get(key, 0) + amount',
        ['Read orders.csv and build region_totals mapping region names to total revenue.', 'Calculate total_revenue.', 'Set top_region to the region with the most revenue.'],
        'import csv\n\n# Read, group, and summarise.\n',
        'import csv\nwith open("orders.csv", newline="", encoding="utf-8") as file:\n    rows = list(csv.DictReader(file))\nregion_totals = {}\nfor row in rows:\n    region = row["region"]\n    region_totals[region] = region_totals.get(region, 0) + float(row["revenue"])\ntotal_revenue = sum(region_totals.values())\ntop_region = max(region_totals, key=region_totals.get)',
        [('Calculate each regional total', 'assert region_totals == {"North": 220, "South": 200, "West": 80}'), ('Calculate the overall total', 'assert total_revenue == 500'), ('Identify the leading region', 'assert top_region == "North"')],
        ['DictReader gives string values; convert revenue.', 'Accumulate into a dictionary keyed by region.', 'Sum the dictionary values and use max(..., key=...get) for the leader.'],
        'Grouping makes the data easier to compare while retaining a check: regional totals should add up to the overall total.', kind='project', minutes=20, files=report_files)
    task(m, 'report-2', 'Sales report · share & ranking',
        'Project 2 / 2. Complete the report with revenue shares and a ranking. sorted() accepts a key function and reverse=True. A lambda is a small unnamed function, useful for describing a sort key.',
        'ranked = sorted(totals, key=totals.get, reverse=True)',
        ['Create shares mapping every region to its percentage of total revenue, rounded to one decimal.', 'Create ranking as region names ordered by descending revenue.', 'Create summary as "North leads with 44.0% of revenue."'],
        'region_totals = {"North": 220, "South": 200, "West": 80}\n',
        'region_totals = {"North": 220, "South": 200, "West": 80}\ntotal = sum(region_totals.values())\nshares = {region: round(value / total * 100, 1) for region, value in region_totals.items()}\nranking = sorted(region_totals, key=region_totals.get, reverse=True)\nleader = ranking[0]\nsummary = f"{leader} leads with {shares[leader]:.1f}% of revenue."',
        [('Calculate shares', 'assert shares == {"North": 44.0, "South": 40.0, "West": 16.0}'), ('Rank regions', 'assert ranking == ["North", "South", "West"]'), ('Write the headline', 'assert summary == "North leads with 44.0% of revenue."')],
        ['Divide each regional total by the overall total and multiply by 100.', 'Sort dictionary keys by their values with reverse=True.', 'Use the first ranked region and its share in an f-string.'],
        'The report now combines a calculation with a concise conclusion. Revenue share alone does not measure profitability; that would require cost data.', kind='project', minutes=20)

    m = module('pandas', 'Analysis with pandas', 'Work with tables using the tools analysts use.', 'Explore a sales dataset')
    task(m, 'table', 'Meet the DataFrame',
        'pandas is a Python library for working with tables. pd.read_csv() returns a DataFrame. df["column"] selects a Series, while df.shape gives (rows, columns). Operations on columns usually apply to every row.',
        'import pandas as pd\ndf = pd.DataFrame({"qty": [2, 3], "price": [5, 8]})\ndf["revenue"] = df["qty"] * df["price"]',
        ['Read sales.csv into df.', 'Add a revenue column from quantity * price.', 'Set total_revenue to the sum of the revenue column.'],
        'import pandas as pd\n',
        'import pandas as pd\ndf = pd.read_csv("sales.csv")\ndf["revenue"] = df["quantity"] * df["price"]\ntotal_revenue = df["revenue"].sum()',
        [('Create a three-row DataFrame', 'import pandas as pd\nassert isinstance(df, pd.DataFrame) and len(df) == 3'), ('Calculate the column', 'assert df["revenue"].tolist() == [10, 24, 5]'), ('Sum the revenue', 'assert total_revenue == 39')],
        ['Use pd.read_csv("sales.csv").', 'Multiplying two columns works row by row.', 'Call .sum() on df["revenue"].'],
        'Column operations express the calculation directly. pandas normally infers numeric CSV types, unlike the standard csv reader.', files=sales)
    task(m, 'select', 'Ask a table a question',
        'A Boolean mask contains one True or False per row. df[mask] keeps the True rows. For multiple conditions, use & and put parentheses around each condition. sort_values() returns a sorted table.',
        'mask = (df["qty"] >= 2) & (df["price"] < 10)\nselected = df[mask]',
        ['Select rows where region is "North" and revenue is at least 100.', 'Sort those rows by revenue descending.', 'Store their product names as a list called products.'],
        'import pandas as pd\ndf = pd.DataFrame({"region": ["North", "South", "North", "North"], "product": ["Tea", "Coffee", "Cake", "Juice"], "revenue": [100, 200, 150, 80]})\n',
        'import pandas as pd\ndf = pd.DataFrame({"region": ["North", "South", "North", "North"], "product": ["Tea", "Coffee", "Cake", "Juice"], "revenue": [100, 200, 150, 80]})\nselected = df[(df["region"] == "North") & (df["revenue"] >= 100)]\nproducts = selected.sort_values("revenue", ascending=False)["product"].tolist()',
        [('Combine filters and sort the result', 'assert products == ["Cake", "Tea"]')],
        ['Build one condition for the region and one for the revenue.', 'Use & with each condition in parentheses.', 'sort_values("revenue", ascending=False), then select product and use tolist().'],
        'Use & for element-by-element Series conditions. Python’s and expects a single truth value and will not combine pandas masks this way.')
    task(m, 'clean', 'Clean a table before grouping',
        'Series.str methods clean a whole text column. pd.to_numeric(..., errors="coerce") turns invalid numeric text into missing values. dropna(subset=[...]) removes rows missing the specified fields. Decide on missing-value rules before grouping.',
        'df["name"] = df["name"].str.strip()\ndf["value"] = pd.to_numeric(df["value"], errors="coerce")',
        ['Strip and lowercase category.', 'Convert amount to numeric, turning invalid text into missing values.', 'Drop rows with missing amounts and reset the index with drop=True. Keep zero amounts.'],
        'import pandas as pd\ndf = pd.DataFrame({"category": [" Food ", "TRAVEL", "Food", "Other"], "amount": ["12", "oops", "8", "0"]})\n',
        'import pandas as pd\ndf = pd.DataFrame({"category": [" Food ", "TRAVEL", "Food", "Other"], "amount": ["12", "oops", "8", "0"]})\ndf["category"] = df["category"].str.strip().str.lower()\ndf["amount"] = pd.to_numeric(df["amount"], errors="coerce")\ndf = df.dropna(subset=["amount"]).reset_index(drop=True)',
        [('Normalise the categories', 'assert df["category"].tolist() == ["food", "food", "other"]'), ('Remove invalid values while retaining zero', 'assert df["amount"].tolist() == [12, 8, 0]'), ('Reset the index', 'assert df.index.tolist() == [0, 1, 2]')],
        ['Chain .str.strip().str.lower().', 'Use errors="coerce" during numeric conversion.', 'Drop only missing amount values, then reset_index(drop=True).'],
        'Zero survives because it is valid data. The invalid amount is missing, so its row is excluded under the rule defined for this exercise.')
    messy = {'shop.csv':'product,quantity,price\n Tea ,2,5\nCoffee,3,8\ntea,4,5\nCake,1,12\nCoffee,unknown,8\nCake,0,12\n'}
    task(m, 'explore-1', 'Sales explorer · prepare the data',
        'Project 1 / 2. You have a small export with an invalid quantity and inconsistent product names. Prepare a trustworthy table before asking which products perform best. Work from the brief; use hints when needed.',
        'df = df.dropna(subset=["quantity"]).copy()',
        ['Read shop.csv into df and normalise product by stripping and lowercasing.', 'Convert quantity to numeric with invalid values coerced to missing.', 'Drop invalid quantities, add revenue = quantity * price, and reset the index. Preserve zero-quantity rows.'],
        'import pandas as pd\n\n# Prepare the sales table.\n',
        'import pandas as pd\ndf = pd.read_csv("shop.csv")\ndf["product"] = df["product"].str.strip().str.lower()\ndf["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")\ndf = df.dropna(subset=["quantity"]).copy().reset_index(drop=True)\ndf["revenue"] = df["quantity"] * df["price"]',
        [('Retain five valid rows', 'assert len(df) == 5 and df["quantity"].tolist() == [2, 3, 4, 1, 0]'), ('Normalise product names', 'assert df["product"].tolist() == ["tea", "coffee", "tea", "cake", "cake"]'), ('Calculate revenue and reset the index', 'assert df["revenue"].tolist() == [10, 24, 20, 12, 0] and df.index.tolist() == list(range(5))')],
        ['Reuse the cleaning operations from the preceding lesson.', 'Convert quantity before dropping rows with missing quantity.', 'After dropping, copy the table and calculate the revenue column.'],
        'The cleaned dataset keeps legitimate zeros and excludes the unparseable quantity. An audit in real work should also report how many rows were excluded and why.', kind='project', minutes=20, files=messy)
    task(m, 'explore-2', 'Sales explorer · group & export',
        'Project 2 / 2. groupby() splits records into groups, applies an operation, then combines the results. reset_index() turns grouped labels back into ordinary columns. Export the result for someone else to use.',
        'summary = df.groupby("category")["value"].sum().reset_index()\nsummary.to_csv("summary.csv", index=False)',
        ['Group df by product and sum revenue into a DataFrame called summary.', 'Sort summary by revenue descending, and reset its index.', 'Save summary to product_summary.csv without a DataFrame index column.', 'Set top_product to the leading product name.'],
        'import pandas as pd\ndf = pd.DataFrame({"product": ["tea", "coffee", "tea", "cake", "cake"], "revenue": [10, 24, 20, 12, 0]})\n',
        'import pandas as pd\ndf = pd.DataFrame({"product": ["tea", "coffee", "tea", "cake", "cake"], "revenue": [10, 24, 20, 12, 0]})\nsummary = df.groupby("product")["revenue"].sum().reset_index()\nsummary = summary.sort_values("revenue", ascending=False).reset_index(drop=True)\nsummary.to_csv("product_summary.csv", index=False)\ntop_product = summary.iloc[0]["product"]',
        [('Group and rank revenue', 'assert summary["product"].tolist() == ["tea", "coffee", "cake"] and summary["revenue"].tolist() == [30, 24, 12]'), ('Export a clean CSV', 'import pandas as pd\nexported = pd.read_csv("product_summary.csv")\nassert exported.columns.tolist() == ["product", "revenue"] and exported["revenue"].tolist() == [30, 24, 12]'), ('Find the leader', 'assert top_product == "tea"')],
        ['Start with df.groupby("product")["revenue"].sum().reset_index().', 'Use sort_values(..., ascending=False), then reset_index(drop=True).', 'to_csv(..., index=False) leaves out the internal index. iloc[0] selects the first row.'],
        'This is a complete analysis pipeline: load, clean, calculate, group, rank, and export. You can adapt it to larger datasets with the same column structure.', kind='project', minutes=20)

    m = module('automation', 'Everyday automation', 'Make repeatable scripts with clear file boundaries.', 'Organise an inbox of files')
    file_set = {'inbox/notes.txt':'Meeting notes', 'inbox/report.csv':'day,total\nMon,10\n', 'inbox/photo.jpg':'sample image placeholder', 'inbox/README.TXT':'Read me', 'inbox/nested/keep.txt':'Nested file'}
    task(m, 'paths', 'Find files with pathlib',
        'pathlib.Path represents a filesystem path. iterdir() lists direct children, is_file() identifies files, name gives the filename, and suffix gives the extension. Comparing suffix.lower() handles uppercase extensions. These lessons operate on generated practice files.',
        'from pathlib import Path\nfor path in Path("inbox").iterdir():\n    if path.is_file():\n        print(path.name)',
        ['Find direct files in inbox whose suffix is .txt, ignoring letter case.', 'Store their names in a sorted list called text_files.', 'Do not include files inside nested folders.'],
        'from pathlib import Path\n',
        'from pathlib import Path\ntext_files = sorted(path.name for path in Path("inbox").iterdir() if path.is_file() and path.suffix.lower() == ".txt")',
        [('Find only direct text files', 'assert text_files == ["README.TXT", "notes.txt"]')],
        ['Use iterdir(), which lists only the direct children.', 'Check is_file() and suffix.lower() == ".txt".', 'Collect path.name and sort the resulting names.'],
        'Explicitly choosing direct children avoids accidentally including an entire directory tree.', files=file_set)
    task(m, 'dates', 'Give reports predictable names',
        'datetime.strptime() parses a date using a format string. strftime() formats it again. %Y is a four-digit year, %m is a two-digit month, and %d is a two-digit day. Dates in filenames sort naturally when written year first.',
        'from datetime import datetime\ndate = datetime.strptime("2026-04-09", "%Y-%m-%d")\nprint(date.strftime("%Y%m%d"))',
        ['Write report_name(date_text), accepting a date formatted YYYY-MM-DD.', 'Return "sales_YYYYMMDD.csv".', 'Let ValueError propagate for an invalid date.'],
        'from datetime import datetime\n\ndef report_name(date_text):\n    pass\n',
        'from datetime import datetime\n\ndef report_name(date_text):\n    date = datetime.strptime(date_text, "%Y-%m-%d")\n    return f"sales_{date:%Y%m%d}.csv"',
        [('Format a report filename', 'assert report_name("2026-04-09") == "sales_20260409.csv"'), ('Handle a leap day', 'assert report_name("2024-02-29") == "sales_20240229.csv"'), ('Reject an impossible date', 'try:\n    report_name("2025-02-29")\nexcept ValueError:\n    pass\nelse:\n    raise AssertionError()')],
        ['Parse the input with datetime.strptime().', 'Use %Y%m%d when formatting the filename.', 'strptime validates the date; do not replace its error with a fabricated date.'],
        'Parsing checks that the date exists. Simply removing hyphens would also accept impossible dates.')
    task(m, 'copy', 'Copy without overwriting',
        'shutil.copy2() copies a file and preserves metadata where possible. Before writing a destination, check whether it already exists. A small reusable helper can express a consistent rule for repeated runs.',
        'from pathlib import Path\nimport shutil\nif not Path("copy.txt").exists():\n    shutil.copy2("source.txt", "copy.txt")',
        ['Write copy_if_new(source, destination).', 'If destination already exists, return False and leave it unchanged.', 'Otherwise copy the file and return True. Source files and destination parent folders will exist.'],
        'from pathlib import Path\nimport shutil\n\ndef copy_if_new(source, destination):\n    pass\n',
        'from pathlib import Path\nimport shutil\n\ndef copy_if_new(source, destination):\n    destination = Path(destination)\n    if destination.exists():\n        return False\n    shutil.copy2(source, destination)\n    return True',
        [('Create a new copy', 'assert copy_if_new("source.txt", "fresh.txt") is True\nassert Path("fresh.txt").read_text() == "new data"'), ('Preserve an existing file', 'assert copy_if_new("source.txt", "existing.txt") is False\nassert Path("existing.txt").read_text() == "keep me"'), ('Handle a repeated run', 'assert copy_if_new("source.txt", "fresh.txt") is False')],
        ['Convert destination to a Path so you can call exists().', 'Return False immediately if it exists.', 'Otherwise call shutil.copy2(), then return True.'],
        'This rule makes repeated single-process runs predictable. Concurrent writers need stronger protection than a separate exists check.', files={'source.txt':'new data','existing.txt':'keep me'})
    task(m, 'organise-1', 'Inbox organiser · plan first',
        'Project 1 / 2. Build a dry-run plan before changing files. Map text files to documents, CSV files to data, and everything else to other. Work on direct files only. Planning makes the proposed changes inspectable.',
        'mapping = {".txt": "documents", ".csv": "data"}\nfolder = mapping.get(extension, "other")',
        ['Create plan as a list of dictionaries with source and destination string paths.', 'Use inbox/<name> as source and organised/<category>/<name> as destination.', 'Sort by source filename, ignore directories, and handle extensions case-insensitively.', 'Do not copy or move any files yet. Use forward slashes in the plan paths.'],
        'from pathlib import Path\n\n# Create a dry-run plan from inbox.\n',
        'from pathlib import Path\nmapping = {".txt": "documents", ".csv": "data"}\nplan = []\nfor path in sorted(Path("inbox").iterdir(), key=lambda p: p.name):\n    if path.is_file():\n        category = mapping.get(path.suffix.lower(), "other")\n        plan.append({"source": path.as_posix(), "destination": f"organised/{category}/{path.name}"})\nprint(plan)',
        [('Plan the correct routes in order', 'assert plan == [{"source": "inbox/README.TXT", "destination": "organised/documents/README.TXT"}, {"source": "inbox/notes.txt", "destination": "organised/documents/notes.txt"}, {"source": "inbox/photo.jpg", "destination": "organised/other/photo.jpg"}, {"source": "inbox/report.csv", "destination": "organised/data/report.csv"}]'), ('Keep the dry run read-only', 'assert not Path("organised").exists() and Path("inbox/notes.txt").exists()')],
        ['Use a suffix-to-category dictionary with an other fallback.', 'Sort Path objects with key=lambda p: p.name.', 'Construct destination strings and append records; do not call copy or rename.'],
        'The plan separates decisions from file operations. In a real automation, review a dry run before applying it to your own folders.', kind='project', minutes=20, files=file_set)
    task(m, 'organise-2', 'Inbox organiser · apply repeatably',
        'Project 2 / 2. Apply a plan by copying files. Create destination folders when needed and skip existing destinations. Calling the function twice should not create duplicate files or overwrite earlier copies.',
        'destination.parent.mkdir(parents=True, exist_ok=True)',
        ['Write apply_plan(plan). Each record contains source and destination.', 'Copy new destinations, keep source files, and skip existing destinations.', 'Return a dictionary containing counts copied and skipped.'],
        'from pathlib import Path\nimport shutil\n\ndef apply_plan(plan):\n    pass\n',
        'from pathlib import Path\nimport shutil\n\ndef apply_plan(plan):\n    copied = 0\n    skipped = 0\n    for entry in plan:\n        destination = Path(entry["destination"])\n        if destination.exists():\n            skipped += 1\n            continue\n        destination.parent.mkdir(parents=True, exist_ok=True)\n        shutil.copy2(entry["source"], destination)\n        copied += 1\n    return {"copied": copied, "skipped": skipped}',
        [('Copy a new destination and preserve the source', 'plan = [{"source": "inbox/notes.txt", "destination": "organised/documents/notes.txt"}]\nassert apply_plan(plan) == {"copied": 1, "skipped": 0}\nassert Path("organised/documents/notes.txt").read_text() == "Meeting notes" and Path("inbox/notes.txt").exists()'), ('Skip existing destinations on a repeat', 'assert apply_plan(plan) == {"copied": 0, "skipped": 1}'), ('Handle an empty plan', 'assert apply_plan([]) == {"copied": 0, "skipped": 0}')],
        ['Track copied and skipped counts as you visit the plan.', 'Check the destination before creating directories or copying.', 'Use mkdir(parents=True, exist_ok=True), then shutil.copy2().'],
        'Your organiser has a planning phase and a repeatable execution phase. It copies practice files, leaving originals intact; every exercise run starts in a fresh temporary folder.', kind='project', minutes=25, files=file_set)

    m = module('web', 'A first step into the web', 'Connect Python data to HTML and API responses.', 'Build a tiny report page')
    task(m, 'html', 'Build a safe HTML fragment',
        'HTML tags describe a page: h1 is a heading and p is a paragraph. If you insert user-provided text into HTML, html.escape() keeps characters such as < and & from becoming markup. This exercise creates HTML text; it does not start a web server.',
        'from html import escape\nname = "Tea & Cake"\nhtml = f"<h1>{escape(name)}</h1>"',
        ['Write heading(name), returning the escaped name inside an h1 tag.', 'Return only that fragment, with no extra surrounding whitespace.'],
        'from html import escape\n\ndef heading(name):\n    pass\n',
        'from html import escape\n\ndef heading(name):\n    return f"<h1>{escape(name)}</h1>"',
        [('Render an ordinary heading', 'assert heading("Sales") == "<h1>Sales</h1>"'), ('Escape special characters', 'assert heading("Tea & Cake") == "<h1>Tea &amp; Cake</h1>"'), ('Treat markup as text', 'assert heading("<script>") == "<h1>&lt;script&gt;</h1>"')],
        ['Escape the name before placing it between tags.', 'Use the imported escape() function.', 'Return f"<h1>{escape(name)}</h1>".'],
        'Escaping prevents text from being interpreted as HTML. It is a habit to preserve when building templates in web frameworks.')
    task(m, 'query', 'Read a query string',
        'A query string is the part after ? in a URL, such as region=North&limit=5. urllib.parse.parse_qs() decodes it into a dictionary of lists because a key can appear multiple times. get() lets you supply a default for a missing key.',
        'from urllib.parse import parse_qs\nparams = parse_qs("city=New+York")\ncity = params["city"][0]',
        ['Write selected_region(query), reading region from the query string.', 'Return the first region value, or "all" when absent or blank.', 'URL-encoded spaces should be decoded.'],
        'from urllib.parse import parse_qs\n\ndef selected_region(query):\n    pass\n',
        'from urllib.parse import parse_qs\n\ndef selected_region(query):\n    params = parse_qs(query)\n    return params.get("region", ["all"])[0]',
        [('Read a region and decode spaces', 'assert selected_region("region=North") == "North" and selected_region("region=New%20York") == "New York"'), ('Handle missing or blank values', 'assert selected_region("") == "all" and selected_region("region=") == "all"'), ('Use the first repeated value', 'assert selected_region("region=North&region=South") == "North"')],
        ['Call parse_qs(query).', 'The values in the returned dictionary are lists.', 'Use params.get("region", ["all"])[0]. Blank values are omitted by default.'],
        'A parser handles URL encoding and repeated parameters consistently. Hand-splitting the string is easy to get wrong.')
    task(m, 'responses', 'Think in requests and responses',
        'An HTTP response has a status, headers, and a body. 200 means success and 404 means not found. Content-Type tells a client how to interpret the body. Here you will model a JSON response as a Python dictionary, without opening a network connection.',
        'import json\nresponse = {"status": 200, "headers": {"Content-Type": "application/json"}, "body": json.dumps({"ok": True})}',
        ['Write route(path). For /api/status, return status 200 with JSON body {"ok": true}.', 'For any other path, return status 404 with JSON body {"error": "Not found"}.', 'Both responses must include headers with Content-Type set to application/json.'],
        'import json\n\ndef route(path):\n    pass\n',
        'import json\n\ndef route(path):\n    if path == "/api/status":\n        status, data = 200, {"ok": True}\n    else:\n        status, data = 404, {"error": "Not found"}\n    return {"status": status, "headers": {"Content-Type": "application/json"}, "body": json.dumps(data)}',
        [('Return a success response', 'import json\nr = route("/api/status")\nassert r["status"] == 200 and json.loads(r["body"]) == {"ok": True}'), ('Return an explicit not-found response', 'r = route("/missing")\nassert r["status"] == 404 and json.loads(r["body"]) == {"error": "Not found"}'), ('Declare JSON content', 'assert route("/api/status")["headers"]["Content-Type"] == "application/json" and route("/other")["headers"]["Content-Type"] == "application/json"')],
        ['Choose status and data based on the path.', 'Use json.dumps(data) for the body string.', 'Return a dictionary with status, headers, and body.'],
        'Routing chooses behavior from a request path. A real server or framework sends these pieces over HTTP; the function here models that boundary.')
    task(m, 'page-1', 'Report page · render your data',
        'Project 1 / 2. Turn your data into an HTML table. Each row uses tr, and each cell uses td. Keep user text escaped and format numeric revenue consistently. Build a reusable renderer from this brief.',
        'row = f"<tr><td>{escape(name)}</td><td>{value:.2f}</td></tr>"',
        ['Write render_rows(records), returning an HTML row for every record with name and revenue.', 'Escape name, format revenue to two decimal places, and preserve input order.', 'Join rows without extra whitespace. An empty list should return an empty string.'],
        'from html import escape\n\ndef render_rows(records):\n    pass\n',
        'from html import escape\n\ndef render_rows(records):\n    return "".join(f"<tr><td>{escape(record[\"name\"])}</td><td>{record[\"revenue\"]:.2f}</td></tr>" for record in records)',
        [('Render ordered rows', 'assert render_rows([{"name": "Tea", "revenue": 30}, {"name": "Cake", "revenue": 12.5}]) == "<tr><td>Tea</td><td>30.00</td></tr><tr><td>Cake</td><td>12.50</td></tr>"'), ('Escape user text', 'assert render_rows([{"name": "<b>A&B</b>", "revenue": 0}]) == "<tr><td>&lt;b&gt;A&amp;B&lt;/b&gt;</td><td>0.00</td></tr>"'), ('Handle empty data', 'assert render_rows([]) == ""')],
        ['Create one string per record, then join the strings.', 'Escape only the name; the table tags should remain markup.', 'Use "".join(...) and format revenue with :.2f.'],
        'The renderer turns records into presentation while keeping text safe. A template engine can do the same job more comfortably for larger pages.', kind='project', minutes=20)
    task(m, 'page-2', 'Report page · finish the page',
        'Project 2 / 2. Put the renderer into a complete HTML document and save it. This is your independent capstone: data becomes a portable page. The checker looks at the HTML structure, so different valid layouts are welcome.',
        'with open("report.html", "w", encoding="utf-8") as file:\n    file.write(page)',
        ['Create a string called page with an HTML document containing head, title, and body.', 'Use "Sales report" as both the title and an h1 heading.', 'Include a table with th headers Product and Revenue, and rows Tea / 30.00 and Cake / 12.00.', 'Write page to report.html using UTF-8. You may reuse the row-rendering pattern from the previous step.'],
        'from html import escape\nrecords = [{"name": "Tea", "revenue": 30}, {"name": "Cake", "revenue": 12}]\n\n# Build and save your report page.\n',
        'from html import escape\nrecords = [{"name": "Tea", "revenue": 30}, {"name": "Cake", "revenue": 12}]\nrows = "".join(f"<tr><td>{escape(r[\"name\"])}</td><td>{r[\"revenue\"]:.2f}</td></tr>" for r in records)\npage = f\'<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Sales report</title></head><body><h1>Sales report</h1><table><tr><th>Product</th><th>Revenue</th></tr>{rows}</table></body></html>\'\nwith open("report.html", "w", encoding="utf-8") as file:\n    file.write(page)',
        [('Include document structure and titles', 'from html.parser import HTMLParser\nclass ReportParser(HTMLParser):\n    def __init__(self):\n        super().__init__(); self.tags=[]; self.stack=[]; self.text={}; self.rows=[]; self.row=None; self.cell=None\n    def handle_starttag(self, tag, attrs):\n        self.tags.append(tag); self.stack.append(tag)\n        if tag == "tr": self.row=[]\n        if tag in ("th", "td"): self.cell=""\n    def handle_data(self, data):\n        for tag in self.stack: self.text[tag]=self.text.get(tag, "")+data\n        if self.cell is not None: self.cell += data\n    def handle_endtag(self, tag):\n        if tag in ("th", "td") and self.row is not None: self.row.append(self.cell.strip()); self.cell=None\n        if tag == "tr" and self.row is not None: self.rows.append(self.row); self.row=None\n        if tag in self.stack: self.stack=self.stack[:len(self.stack)-1-self.stack[::-1].index(tag)]\np = ReportParser(); p.feed(page)\nassert all(tag in p.tags for tag in ("html", "head", "body", "title", "h1", "table"))\nassert p.text.get("title", "").strip() == "Sales report" and p.text.get("h1", "").strip() == "Sales report"'), ('Include headers and revenue rows', 'assert ["Product", "Revenue"] in p.rows and ["Tea", "30.00"] in p.rows and ["Cake", "12.00"] in p.rows'), ('Save the complete page', 'from pathlib import Path\nassert Path("report.html").read_text(encoding="utf-8") == page')],
        ['Start with an HTML document skeleton, then place the heading and table inside body.', 'Generate the data rows from records and include a header row with th cells.', 'Assemble the fragments into page, then write page to report.html.'],
        'You have gone from Python fundamentals to cleaning data, building repeatable scripts, and generating a web page. Next, you can adapt these projects to your own sample data or explore a framework such as Flask or Django.', kind='project', minutes=25)
